add_executable(conflux_json_tests json_test.cxx)
target_link_libraries(conflux_json_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_builder_tests json_builder_test.cxx)
target_link_libraries(conflux_json_builder_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_codec_array_tests json_codec_array_test.cxx)
target_link_libraries(conflux_json_codec_array_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_codec_builtin_tests json_codec_builtin_test.cxx)
target_link_libraries(conflux_json_codec_builtin_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_codec_custom_tests json_codec_custom_test.cxx)
target_link_libraries(conflux_json_codec_custom_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_codec_encode_tests json_codec_encode_test.cxx)
target_link_libraries(conflux_json_codec_encode_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_codec_members_tests json_codec_members_test.cxx)
target_link_libraries(conflux_json_codec_members_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_codec_optional_member_tests json_codec_optional_member_test.cxx)
target_link_libraries(conflux_json_codec_optional_member_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_codec_map_tests json_codec_map_test.cxx)
target_link_libraries(conflux_json_codec_map_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_codec_pair_tuple_tests json_codec_pair_tuple_test.cxx)
target_link_libraries(conflux_json_codec_pair_tuple_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_document_tests json_document_test.cxx)
target_link_libraries(conflux_json_document_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_dom_path_tests json_dom_path_test.cxx)
target_link_libraries(conflux_json_dom_path_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_dump_tests json_dump_test.cxx)
target_link_libraries(conflux_json_dump_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_examples_tests json_examples_test.cxx)
target_link_libraries(conflux_json_examples_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_error_tests json_error_test.cxx)
target_link_libraries(conflux_json_error_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_input_model_tests json_input_model_test.cxx)
target_link_libraries(conflux_json_input_model_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_parse_container_tests json_parse_container_test.cxx)
target_link_libraries(conflux_json_parse_container_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_parse_conformance_tests json_parse_conformance_test.cxx)
target_link_libraries(conflux_json_parse_conformance_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_parse_error_tests json_parse_error_test.cxx)
target_link_libraries(conflux_json_parse_error_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_parse_scalar_tests json_parse_scalar_test.cxx)
target_link_libraries(conflux_json_parse_scalar_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_nullable_tests json_nullable_test.cxx)
target_link_libraries(conflux_json_nullable_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_number_model_tests json_number_model_test.cxx)
target_link_libraries(conflux_json_number_model_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_node_ref_tests json_node_ref_test.cxx)
target_link_libraries(conflux_json_node_ref_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_object_lookup_tests json_object_lookup_test.cxx)
target_link_libraries(conflux_json_object_lookup_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_parse_limits_tests json_parse_limits_test.cxx)
target_link_libraries(conflux_json_parse_limits_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_pointer_tests json_pointer_test.cxx)
target_link_libraries(conflux_json_pointer_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)
add_executable(conflux_json_reader_tests json_reader_test.cxx)
target_link_libraries(conflux_json_reader_tests PRIVATE conflux conflux_options Catch2::Catch2WithMain)

if(_conflux_simd_selection STREQUAL "RUNTIME" AND CONFLUX_JSON_STDSIMD_IFUNC AND TARGET conflux_json)
    add_executable(conflux_json_simd_ifunc_test json_simd_ifunc_test.cxx)
    target_link_libraries(conflux_json_simd_ifunc_test PRIVATE conflux_json conflux_options)
    foreach(_conflux_json_simd_ifunc_variant IN ITEMS scalar sse2 avx2)
        add_test(NAME simd/json-ifunc-${_conflux_json_simd_ifunc_variant}
            COMMAND conflux_json_simd_ifunc_test ${_conflux_json_simd_ifunc_variant})
        set_tests_properties(simd/json-ifunc-${_conflux_json_simd_ifunc_variant} PROPERTIES
            ENVIRONMENT "CONFLUX_TEST_JSON_SIMD_IFUNC=${_conflux_json_simd_ifunc_variant}"
            LABELS "simd;json"
            RUN_SERIAL TRUE)
    endforeach()
endif()

if(TARGET conflux_json_native_provider)
    add_executable(conflux_json_boundary_tests json_boundary_test.cxx)
    target_link_libraries(conflux_json_boundary_tests
        PRIVATE conflux_json_native_provider conflux_options Catch2::Catch2WithMain)
endif()

if(TARGET conflux_json_file)
    add_executable(conflux_json_file_tests json_file_test.cxx)
    target_link_libraries(conflux_json_file_tests
        PRIVATE conflux_json_file conflux_file_io_sync conflux_options Catch2::Catch2WithMain)
endif()

if(CONFLUX_JSON_REFLECT)
    # Under P2996 -freflection, including Catch2 headers in any TU that
    # also imports modules compiled with -freflection causes pthreadtypes conflicts.
    # Use a standalone test module + thin main instead of Catch2.
    add_executable(conflux_json_reflect_tests)
    target_sources(conflux_json_reflect_tests
        PRIVATE
            json_reflection_main.cxx
        PRIVATE FILE_SET CXX_MODULES FILES
            json_reflection_test.cxx)
    target_link_libraries(conflux_json_reflect_tests
        PRIVATE conflux_types conflux_json conflux_json_reflect conflux_json_reflect_provider conflux_options)
    target_compile_options(conflux_json_reflect_tests PRIVATE ${CONFLUX_REFLECTION_COMPILE_OPTIONS})
    add_test(NAME conflux_json_reflect_tests COMMAND conflux_json_reflect_tests)
    set_tests_properties(conflux_json_reflect_tests PROPERTIES RUN_SERIAL TRUE)
endif()

add_executable(conflux_json_conformance_external json_conformance_external.cxx)
target_link_libraries(conflux_json_conformance_external PRIVATE conflux conflux_options Catch2::Catch2WithMain)

if(CONFLUX_HAS_JSON_TESTSUITE)
    add_executable(conflux_json_testsuite_gate json_testsuite_gate.cxx)
    target_link_libraries(conflux_json_testsuite_gate PRIVATE conflux conflux_options Catch2::Catch2WithMain)
    target_compile_definitions(conflux_json_testsuite_gate PRIVATE "JSONTESTSUITE_DIR=\"${JSONTESTSUITE_DIR}\"")
endif()
