include(CTest)

conflux_discover_tests(conflux_tests)
if(CONFLUX_HAS_TLS STREQUAL "true")
    conflux_discover_tests(conflux_tls_external)
endif()
conflux_discover_tests(conflux_crypto_tests)
conflux_discover_tests(conflux_utils_tests)
if(TARGET conflux_jwt_tests)
    conflux_discover_tests(conflux_jwt_tests)
endif()
conflux_discover_tests(conflux_password_hash_tests)
if(TARGET conflux_auth_secret_config_tests)
    conflux_discover_tests(conflux_auth_secret_config_tests)
endif()
conflux_discover_tests(conflux_auth_rate_limit_tests)
if(TARGET conflux_config_tests)
    conflux_discover_tests(conflux_config_tests)
endif()
if(TARGET conflux_http_core_tests)
    conflux_discover_tests(conflux_http_core_tests)
endif()
if(TARGET conflux_http_facade_tests)
    conflux_discover_tests(conflux_http_facade_tests)
endif()
if(TARGET conflux_http_metrics_e2e)
    conflux_discover_tests(conflux_http_metrics_e2e)
endif()

if(TARGET conflux_http_facade_import_smoke)
    conflux_discover_tests(conflux_http_facade_import_smoke)
endif()
if(TARGET conflux_http_response_tests)
    conflux_discover_tests(conflux_http_response_tests)
endif()
if(TARGET conflux_http_json_tests)
    conflux_discover_tests(conflux_http_json_tests)
endif()
if(TARGET conflux_http_server_helpers_tests)
    conflux_discover_tests(conflux_http_server_helpers_tests)
endif()
if(TARGET conflux_send_zc_lifecycle_tests)
    conflux_discover_tests(conflux_send_zc_lifecycle_tests)
endif()
conflux_discover_tests(conflux_template_tests)
conflux_discover_tests(conflux_json_tests)
if(TARGET conflux_json_file_tests)
    conflux_discover_tests(conflux_json_file_tests)
endif()
conflux_discover_tests(conflux_json_conformance_external)
if(TARGET conflux_json_testsuite_gate)
    conflux_discover_tests(conflux_json_testsuite_gate)
endif()
conflux_discover_tests(conflux_process_tests)
conflux_discover_tests(conflux_resource_tests)
if(TARGET conflux_recv_bundle_tests)
    conflux_discover_tests(conflux_recv_bundle_tests)
endif()
if(TARGET conflux_incremental_buf_ring_tests)
    conflux_discover_tests(conflux_incremental_buf_ring_tests)
endif()
conflux_discover_tests(conflux_tcp_listener_tests)
if(TARGET conflux_recv_bundle_e2e_tests)
    conflux_discover_tests(conflux_recv_bundle_e2e_tests)
endif()
if(CONFLUX_ENABLE_TSAN)
    conflux_discover_tests(conflux_work_tests TEST_SPEC "~[stress]")
    conflux_discover_stress_tests(conflux_work_tests TEST_SPEC "[stress]")
else()
    conflux_discover_tests(conflux_work_tests)
endif()
conflux_discover_tests(conflux_work_root_tests)
conflux_discover_tests(conflux_work_race_tests)
conflux_discover_tests(conflux_work_carrier_tests)
conflux_discover_tests(conflux_work_carrier_phase2_tests)
conflux_discover_tests(conflux_work_carrier_phase3_tests)
conflux_discover_tests(conflux_work_carrier_phase4_tests)
conflux_discover_tests(conflux_work_carrier_phase5_tests)
conflux_discover_tests(conflux_work_carrier_phase6_tests)
conflux_discover_tests(conflux_work_carrier_streams_tests)
conflux_discover_tests(conflux_work_carrier_timer_tests)
conflux_discover_tests(conflux_uring_flow_tests)
conflux_discover_tests(conflux_owned_path_flow_tests)
conflux_discover_tests(conflux_direct_slot_pool_tests)
conflux_discover_tests(conflux_cq_overflow_tests)
if(TARGET conflux_ring_resize_tests)
    conflux_discover_tests(conflux_ring_resize_tests)
endif()
conflux_discover_tests(conflux_uring_caps_tests)
conflux_discover_tests(conflux_poll_first_auto_tests)
conflux_discover_tests(conflux_direct_accept_sqe_tests)
conflux_discover_tests(conflux_file_io_tests)
conflux_discover_tests(conflux_file_io_sync_tests)
conflux_discover_tests(conflux_dns_codec_tests)
conflux_discover_tests(conflux_dns_resolver_tests)
conflux_discover_tests(conflux_udp_tests)
conflux_discover_tests(conflux_socket_task_ring_tests)
conflux_discover_tests(conflux_client_cancellation_e2e)
conflux_discover_tests(conflux_file_io_http_e2e)
conflux_discover_tests(conflux_proxy_hostile_upstream_e2e)
conflux_discover_tests(conflux_http_proxy_e2e)
conflux_discover_tests(conflux_http_cookie_signing_e2e)
conflux_discover_tests(conflux_http_csrf_e2e)
conflux_discover_tests(conflux_http_etag_e2e)
conflux_discover_tests(conflux_http_response_cache_e2e)
conflux_discover_tests(conflux_http_tracing_e2e)
conflux_discover_tests(conflux_http_request_id_e2e)
conflux_discover_tests(conflux_http_vhost_e2e)
conflux_discover_tests(conflux_http_openapi_e2e)
conflux_discover_tests(conflux_http_structured_log_e2e)
conflux_discover_tests(conflux_compression_matrix_e2e)
conflux_discover_tests(conflux_chaos_resource_e2e)
conflux_discover_tests(conflux_observability_golden_e2e)
conflux_discover_tests(conflux_http_slowloris_e2e)
conflux_discover_tests(conflux_http_backpressure_e2e)
conflux_discover_stress_tests(conflux_http_full_drain_contract_e2e)
conflux_discover_stress_tests(conflux_http_overflow_stress_tests)
if(CONFLUX_EFFECTIVE_SMTP)
    conflux_discover_tests(conflux_smtp_tests)
endif()
if(TARGET conflux_libcurl_external)
    conflux_discover_tests(conflux_libcurl_external)
endif()
if(TARGET conflux_libcurl_external_stress)
    conflux_discover_stress_tests(conflux_libcurl_external_stress)
endif()
if(CONFLUX_HAS_HTTP2 STREQUAL "true")
    conflux_discover_tests(conflux_h2_external)
endif()
if(CONFLUX_HAS_HTTP3 STREQUAL "true")
    conflux_discover_tests(conflux_h3_external)
endif()
if(CONFLUX_HAS_DB STREQUAL "true")
    conflux_discover_tests(conflux_db_tests)
    conflux_discover_db_integration_tests(conflux_db_integration)
endif()
