#!/usr/bin/env bash
set -euo pipefail

source_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
stage_dir="${CONFLUX_RELEASE_GENERATED_HEADERS_STAGE:-${TMPDIR:-/tmp}/conflux-release-generated-headers/stage}"

"$source_root/scripts/stage-release-artifacts.sh" \
    --stage-dir "$stage_dir" \
    --no-tarball

source_include="$stage_dir/source/include"
install_include="$stage_dir/install/include"

if [[ ! -d "$source_include/conflux" ]]; then
    printf 'check-release-generated-headers-policy: missing source/include/conflux\n' >&2
    exit 1
fi
if [[ ! -d "$install_include/conflux" ]]; then
    printf 'check-release-generated-headers-policy: missing install/include/conflux\n' >&2
    exit 1
fi

if ! diff -qr "$install_include" "$source_include" >/dev/null; then
    printf 'check-release-generated-headers-policy: source/include differs from install/include\n' >&2
    diff -qr "$install_include" "$source_include" >&2 || true
    exit 1
fi

generated_headers=(
    "$source_include/conflux/features.hxx"
    "$source_include/conflux/json.hxx"
)
for header in "${generated_headers[@]}"; do
    if ! grep -Fqx '// Generated by scripts/module_header_bridge.py; do not edit by hand.' "$header"; then
        printf 'check-release-generated-headers-policy: missing generated banner in %s\n' \
            "${header#"$stage_dir/"}" >&2
        exit 1
    fi
done

if ! grep -qx 'generated_header_artifact=install/include/conflux' \
        "$stage_dir/release-artifact-manifest.txt"; then
    printf 'check-release-generated-headers-policy: manifest does not record install generated headers\n' >&2
    exit 1
fi
if ! grep -qx 'source_generated_header_artifact=source/include/conflux' \
        "$stage_dir/release-artifact-manifest.txt"; then
    printf 'check-release-generated-headers-policy: manifest does not record source generated headers\n' >&2
    exit 1
fi

printf 'check-release-generated-headers-policy: ok (%s)\n' "$source_include/conflux"
