#!/usr/bin/env python3
"""Generate header-mode public APIs from C++ module interface units.

This is a mechanical bridge for the current conflux layout: module interface units
remain the authoring source, generated .hxx headers become the compatibility
surface, and generated module wrappers include those headers from the global
module fragment, then re-export the selected names.

The generated output is intentionally conservative. It is meant to remove the
large, error-prone first migration step, then leave a small review surface for
modules that use complex exported namespace blocks or unusual declarations.
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import re
import shutil
import sys
from pathlib import Path
from typing import Iterable

MODULE_DECL_RE = re.compile(r"^(?P<indent>\s*)(?P<export>export\s+)?module\s+(?P<name>[A-Za-z_][A-Za-z0-9_.]*(?::[A-Za-z_][A-Za-z0-9_]*)?)\s*;")
IMPORT_RE = re.compile(
    r"^(?P<indent>\s*)(?P<export>export\s+)?import\s+"
    r"(?P<name>[A-Za-z_][A-Za-z0-9_.]*:[A-Za-z_][A-Za-z0-9_]*|[A-Za-z_][A-Za-z0-9_.]*|std(?:\.compat)?|:[A-Za-z_][A-Za-z0-9_]*)\s*;"
)
EXPORT_PREFIX_RE = re.compile(r"^(?P<indent>\s*)export\s+")
NAMESPACE_RE = re.compile(r"^\s*(?:export\s+)?namespace\s+(?P<name>[A-Za-z_][A-Za-z0-9_:]*)\s*\{")
TOP_TYPE_RE = re.compile(r"^\s*export\s+(?:template\s*<[^>]+>\s*)?(?:(?:class|struct|union)\s+|enum\s+class\s+|enum\s+)(?P<name>[A-Za-z_][A-Za-z0-9_]*)\b")
USING_RE = re.compile(r"^\s*export\s+using\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\b")
VAR_RE = re.compile(r"^\s*export\s+(?:inline\s+)?(?:constexpr\s+|constinit\s+|const\s+)*[A-Za-z_:][A-Za-z0-9_:<>\s,&*]*\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*(?:[={;])")
FUNC_RE = re.compile(r"^\s*export\s+(?:constexpr\s+|consteval\s+|inline\s+|auto\s+|static\s+|friend\s+)*[A-Za-z_:~][A-Za-z0-9_:<>\s,&*]*\s+(?P<name>[A-Za-z_~][A-Za-z0-9_]*)\s*\(")
TEMPLATE_LINE_RE = re.compile(r"^\s*export\s+template\s*<")
STD_TOKEN_RE = re.compile(r"\bstd::([A-Za-z_][A-Za-z0-9_]*)\b")
BARE_STD_TOKEN_RE = re.compile(r"(?<![A-Za-z0-9_:])(?P<name>size_t|uint8_t|uint16_t|uint32_t|uint64_t|int8_t|int16_t|int32_t|int64_t|byte)\b")
BARE_NULLPTR_T_RE = re.compile(r"(?<![A-Za-z0-9_:])nullptr_t\b")
LOCAL_INCLUDE_RE = re.compile(r'^(?P<indent>\s*)#\s*include\s+"(?P<path>[^"]+)"')
ANGLE_INCLUDE_RE = re.compile(r"^\s*#\s*include\s*<(?P<header>[^>]+)>")
CONFLUX_MACRO_RE = re.compile(r"\bCONFLUX_[A-Z0-9_]+\b")
DIRECT_IF_MACRO_RE = re.compile(r"^\s*#\s*(?:if|elif)\s+(CONFLUX_[A-Z0-9_]+)\b")
PROBABLE_FUNCTION_LINE_RE = re.compile(r"^(?P<indent>\s*)(?P<export>export\s+)?(?P<prefix>(?:\[\[[^\]]+\]\]\s*)*)(?P<body>[^#/{;]*\b[A-Za-z_~][A-Za-z0-9_:~]*\s*\([^;]*)(?P<tail>.*)$")

PROJECT_IMPORT_PREFIXES = ("conflux.",)
LEGACY_PROJECT_MODULE_PREFIXES = ("conflux_",)
GENERATED_BANNER = "// Generated by scripts/module_header_bridge.py; do not edit by hand."
CONFIG_HEADER_RELPATH = Path("conflux/config.hxx")
FEATURES_HEADER_RELPATH = Path("conflux/features.hxx")
PRIVATE_INCLUDE_PREFIX = Path("conflux/detail/generated")

# Deliberately not inferred. Public header mode should not paper over iostream
# dependencies; conflux keeps streams out of reusable source and fixes those first.
STD_STREAM_TOKENS = {
    "cin", "cout", "cerr", "clog",
    "istream", "ostream", "iostream",
    "ifstream", "ofstream", "fstream",
    "istringstream", "ostringstream", "stringstream",
}
STREAM_TOKEN_HEADER = {
    "cin": "iostream",
    "cout": "iostream",
    "cerr": "iostream",
    "clog": "iostream",
    "istream": "iostream",
    "ostream": "iostream",
    "iostream": "iostream",
    "ifstream": "fstream",
    "ofstream": "fstream",
    "fstream": "fstream",
    "istringstream": "sstream",
    "ostringstream": "sstream",
    "stringstream": "sstream",
}

STD_HEADER_BY_TOKEN: dict[str, set[str]] = {
    "abort": {"cstdlib"},
    "accumulate": {"numeric"},
    "addressof": {"memory"},
    "array": {"array"},
    "atomic": {"atomic"},
    "bad_alloc": {"new"},
    "barrier": {"barrier"},
    "bit_cast": {"bit"},
    "byte": {"cstddef"},
    "chrono": {"chrono"},
    "condition_variable": {"condition_variable"},
    "coroutine_handle": {"coroutine"},
    "suspend_never": {"coroutine"},
    "suspend_always": {"coroutine"},
    "noop_coroutine": {"coroutine"},
    "coroutine_traits": {"coroutine"},
    "exception_ptr": {"exception"},
    "current_exception": {"exception"},
    "rethrow_exception": {"exception"},
    "queue": {"queue"},
    "mt19937": {"random"},
    "random_device": {"random"},
    "set": {"set"},
    "list": {"list"},
    "less": {"functional"},
    "greater": {"functional"},
    "numeric_limits": {"limits"},
    "exchange": {"utility"},
    "launder": {"new"},
    "copy": {"algorithm"},
    "count": {"algorithm"},
    "deque": {"deque"},
    "enable_if_t": {"type_traits"},
    "endian": {"bit"},
    "equal": {"algorithm"},
    "error_code": {"system_error"},
    "expected": {"expected"},
    "filesystem": {"filesystem"},
    "find": {"algorithm"},
    "forward": {"utility"},
    "from_chars": {"charconv"},
    "function": {"functional"},
    "future": {"future"},
    "future_status": {"future"},
    "generic_category": {"system_error"},
    "hash": {"functional"},
    "initializer_list": {"initializer_list"},
    "isfinite": {"cmath"},
    "in_place": {"utility"},
    "in_place_type": {"variant"},
    "invoke": {"functional"},
    "is_same_v": {"type_traits"},
    "jthread": {"thread"},
    "make_unique": {"memory"},
    "map": {"map"},
    "max": {"algorithm"},
    "memory_order": {"atomic"},
    "move": {"utility"},
    "mutex": {"mutex"},
    "nullopt": {"optional"},
    "optional": {"optional"},
    "pair": {"utility"},
    "pmr": {"memory_resource"},
    "ranges": {"algorithm", "ranges"},
    "remove_cvref_t": {"type_traits"},
    "span": {"span"},
    "source_location": {"source_location"},
    "spanstream": {"spanstream"},
    "shared_ptr": {"memory"},
    "shared_lock": {"shared_mutex"},
    "shared_mutex": {"shared_mutex"},
    "sort": {"algorithm"},
    "stop_source": {"stop_token"},
    "stop_token": {"stop_token"},
    "strlen": {"cstring"},
    "string": {"string"},
    "string_view": {"string_view"},
    "system_error": {"system_error"},
    "thread": {"thread"},
    "to_chars": {"charconv"},
    "tuple": {"tuple"},
    "type_identity": {"type_traits"},
    "type_index": {"typeindex"},
    "uint8_t": {"cstdint"},
    "uint16_t": {"cstdint"},
    "uint32_t": {"cstdint"},
    "uint64_t": {"cstdint"},
    "int8_t": {"cstdint"},
    "int16_t": {"cstdint"},
    "int32_t": {"cstdint"},
    "int64_t": {"cstdint"},
    "unique_ptr": {"memory"},
    "unordered_map": {"unordered_map"},
    "unordered_set": {"unordered_set"},
    "variant": {"variant"},
    "vector": {"vector"},
}

STD_COMPAT_FALLBACK_HEADERS = {
    "cassert",
    "cctype",
    "cerrno",
    "cfloat",
    "cinttypes",
    "climits",
    "cmath",
    "cstddef",
    "cstdint",
    "cstdio",
    "cstdlib",
    "cstring",
    "ctime",
}

# Used only when inference sees standard-library use but cannot identify a more
# precise header. Keeps generated compatibility headers useful instead of brittle.
STD_SAFETY_NET_HEADERS = {
    "algorithm",
    "array",
    "atomic",
    "bit",
    "charconv",
    "chrono",
    "concepts",
    "cstddef",
    "cstdint",
    "expected",
    "functional",
    "coroutine",
    "exception",
    "new",
    "limits",
    "queue",
    "random",
    "set",
    "list",
    "mutex",
    "condition_variable",
    "numeric",
    "deque",
    "map",
    "unordered_map",
    "unordered_set",
    "source_location",
    "memory",
    "memory_resource",
    "optional",
    "span",
    "string",
    "string_view",
    "system_error",
    "tuple",
    "type_traits",
    "utility",
    "variant",
    "vector",
}

KNOWN_STD_HEADERS = (
    STD_SAFETY_NET_HEADERS
    | set(STREAM_TOKEN_HEADER.values())
    | {header for headers in STD_HEADER_BY_TOKEN.values() for header in headers}
)


@dataclasses.dataclass(frozen=True)
class ModuleUnit:
    path: Path
    relpath: Path
    module_name: str
    is_interface: bool
    is_partition: bool
    declaration_index: int
    imports: tuple[str, ...]
    export_imports: tuple[str, ...]
    uses_std: bool
    uses_std_compat: bool
    lines: tuple[str, ...]


@dataclasses.dataclass(frozen=True)
class ExportSymbol:
    namespace: str | None
    name: str


def read_lines(path: Path) -> list[str]:
    return path.read_text(encoding="utf-8").splitlines(keepends=True)


def discover_module_unit(path: Path, src_root: Path) -> ModuleUnit | None:
    lines = read_lines(path)
    if any(GENERATED_BANNER in line for line in lines):
        return None
    declaration_index = -1
    module_name = ""
    is_interface = False
    for index, line in enumerate(lines):
        match = MODULE_DECL_RE.match(line)
        if match is None:
            continue
        declaration_index = index
        module_name = match.group("name")
        is_interface = bool(match.group("export"))
        break
    if declaration_index < 0:
        return None

    imports: list[str] = []
    export_imports: list[str] = []
    uses_std = False
    uses_std_compat = False
    for line in lines[declaration_index + 1 :]:
        match = IMPORT_RE.match(line)
        if match is None:
            continue
        name = match.group("name")
        is_export = bool(match.group("export"))
        if name == "std":
            uses_std = True
        elif name == "std.compat":
            uses_std_compat = True
        elif is_export:
            export_imports.append(name)
        elif name.startswith(":"):
            imports.append(name)
        else:
            imports.append(name)
    return ModuleUnit(
        path=path,
        relpath=path.relative_to(src_root),
        module_name=module_name,
        is_interface=is_interface,
        is_partition=":" in module_name,
        declaration_index=declaration_index,
        imports=tuple(imports),
        export_imports=tuple(export_imports),
        uses_std=uses_std,
        uses_std_compat=uses_std_compat,
        lines=tuple(lines),
    )


def module_to_header_relpath(module_name: str) -> Path:
    primary, sep, partition = module_name.partition(":")
    parts = primary.split(".")
    if sep:
        return Path(*parts, partition).with_suffix(".hxx")
    return Path(*parts).with_suffix(".hxx")


def import_to_include(import_name: str, owner_module: str | None = None) -> str | None:
    if import_name.startswith(":"):
        if owner_module is None:
            return None
        primary = owner_module.split(":", 1)[0]
        return module_to_header_relpath(f"{primary}{import_name}").as_posix()
    if import_name == "conflux" or any(import_name.startswith(prefix) for prefix in PROJECT_IMPORT_PREFIXES):
        return module_to_header_relpath(import_name).as_posix()
    if any(import_name.startswith(prefix) for prefix in LEGACY_PROJECT_MODULE_PREFIXES):
        return Path(import_name).with_suffix(".hxx").as_posix()
    return None


def infer_standard_headers(text: str, uses_std_compat: bool) -> list[str]:
    headers: set[str] = set()
    seen_tokens = set(STD_TOKEN_RE.findall(text)) | {m.group("name") for m in BARE_STD_TOKEN_RE.finditer(text)}
    unknown_std_tokens: set[str] = set()
    for token in seen_tokens:
        if token in STD_STREAM_TOKENS:
            continue
        token_headers = STD_HEADER_BY_TOKEN.get(token)
        if token_headers is None:
            unknown_std_tokens.add(token)
        else:
            headers.update(token_headers)
    if uses_std_compat:
        headers.update(STD_COMPAT_FALLBACK_HEADERS)
    if unknown_std_tokens:
        headers.update(STD_SAFETY_NET_HEADERS)
    return sorted(headers)


def find_std_stream_tokens(text: str, explicit_headers: set[str] | None = None) -> list[str]:
    explicit_headers = explicit_headers or set()
    seen_tokens = set(STD_TOKEN_RE.findall(text))
    tokens = seen_tokens & STD_STREAM_TOKENS
    return sorted(token for token in tokens if STREAM_TOKEN_HEADER.get(token) not in explicit_headers)


def explicit_std_headers(lines: Iterable[str]) -> set[str]:
    headers: set[str] = set()
    for line in lines:
        stripped = line.strip()
        if not stripped.startswith("#include <"):
            continue
        end = stripped.find(">", len("#include <"))
        if end != -1:
            headers.add(stripped[len("#include <"):end])
    return headers


def angle_include_header(line: str) -> str | None:
    match = ANGLE_INCLUDE_RE.match(line)
    if match is None:
        return None
    return match.group("header")


def is_known_std_header(header: str) -> bool:
    return header in KNOWN_STD_HEADERS


def rebase_local_include_line(line: str) -> str:
    match = LOCAL_INCLUDE_RE.match(line)
    if match is None:
        return line
    rel = Path(match.group("path"))
    if rel.is_absolute() or ".." in rel.parts:
        return line
    target = PRIVATE_INCLUDE_PREFIX / rel
    return f"{match.group('indent')}#include <{target.as_posix()}>\n"

def module_unit_stem(module_name: str) -> str:
    primary, sep, partition = module_name.partition(":")
    stem = "/".join(primary.split("."))
    if sep:
        return f"{stem}/{partition}"
    return stem


def source_line_feature_macros(lines: Iterable[str]) -> list[str]:
    macros: set[str] = set()
    for line in lines:
        match = DIRECT_IF_MACRO_RE.match(line)
        if match is not None:
            macros.add(match.group(1))
    return sorted(macros)


def line_needs_header_inline(line: str) -> bool:
    stripped = line.lstrip()
    if not stripped or stripped.startswith(("//", "#")):
        return False
    if stripped.rstrip().endswith(";"):
        return False
    # Header mode only needs implicit inline for real file-scope definitions.
    # Declarations are intentionally left as declarations because compiled
    # implementation units still provide the out-of-line symbols.
    if "{" not in stripped:
        return False
    semicolon_pos = stripped.find(";")
    brace_pos = stripped.find("{")
    if semicolon_pos != -1 and semicolon_pos < brace_pos:
        return False
    if line[: len(line) - len(stripped)] and not stripped.startswith("export "):
        return False
    probe = stripped.removeprefix("export ")
    probe_no_attrs = re.sub(r"^(?:\[\[[^\]]+\]\]\s*)+", "", probe)
    if probe_no_attrs.startswith((
        "inline ", "static ", "constexpr ", "consteval ", "friend ",
        "class ", "struct ", "union ", "enum ", "namespace ", "using ",
        "template ", "concept ", "requires ", "if ", "for ", "while ", "switch ",
        "return ", "co_return ", "static_assert", "extern ",
    )):
        return False
    match = PROBABLE_FUNCTION_LINE_RE.match(line)
    if match is None:
        return False
    body = match.group("body")
    lhs = body.split("(", 1)[0].strip()
    if lhs == "main" or lhs.endswith(" main"):
        return False
    if "=" in lhs:
        return False
    if "->" in line and re.fullmatch(r"[A-Za-z_][A-Za-z0-9_:]*", lhs):
        return False
    if body.strip().startswith(("auto [", "decltype(")):
        return False
    return True


def headerize_source_line(line: str, force_inline: bool = False) -> str:
    line = rebase_local_include_line(line)
    line = BARE_NULLPTR_T_RE.sub("std::nullptr_t", line)
    if IMPORT_RE.match(line):
        return line
    stripped_original = line.lstrip()
    was_export = stripped_original.startswith("export ")
    line = EXPORT_PREFIX_RE.sub(lambda match: match.group("indent"), line, count=1)
    if was_export:
        stripped = line.lstrip()
        indent = line[: len(line) - len(stripped)]
        variable_like = "(" not in stripped and ("=" in stripped or ";" in stripped or "{" in stripped)
        if variable_like and stripped.startswith("constexpr ") and not stripped.startswith("inline constexpr "):
            return f"{indent}inline {stripped}"
        if variable_like and stripped.startswith("constinit ") and not stripped.startswith("inline constinit "):
            return f"{indent}inline {stripped}"
    if force_inline or line_needs_header_inline(line):
        match = PROBABLE_FUNCTION_LINE_RE.match(line)
        if match is not None:
            body = match.group("body")
            body_prefix = body.split("(", 1)[0]
            if " inline " in f" {body_prefix} ":
                return line
            body_stripped = body.lstrip()
            body_indent = body[: len(body) - len(body_stripped)]
            extern_c_prefix = 'extern "C" '
            if body_stripped.startswith(extern_c_prefix):
                return (
                    f"{match.group('indent')}{match.group('prefix')}"
                    f"{body_indent}{extern_c_prefix}inline "
                    f"{body_stripped.removeprefix(extern_c_prefix)}{match.group('tail')}\n"
                )
            return f"{match.group('indent')}{match.group('prefix')}inline {body}{match.group('tail')}\n"
    return line


def starts_multiline_function_definition(lines: list[str], index: int) -> bool:
    line = lines[index]
    stripped = line.lstrip()
    if line[: len(line) - len(stripped)] and not stripped.startswith("export "):
        return False
    if stripped.startswith((
        "return ", "co_return ", "if ", "for ", "while ", "switch ",
        "requires ", "static_assert", "class ", "struct ", "union ",
        "enum ", "using ", "namespace ", "concept ",
    )):
        return False
    if not stripped.rstrip().endswith("("):
        return False
    if PROBABLE_FUNCTION_LINE_RE.match(line) is None:
        return False
    paren_depth = line.count("(") - line.count(")")
    for next_line in lines[index + 1 :]:
        for char in next_line:
            if char == "(":
                paren_depth += 1
                continue
            if char == ")":
                paren_depth -= 1
                continue
            if paren_depth > 0:
                continue
            if char == "{":
                return True
            if char == ";":
                return False
    return False


def module_overlay_source_line(line: str) -> str:
    line = rebase_local_include_line(line)
    return BARE_NULLPTR_T_RE.sub("std::nullptr_t", line)


def header_impl_source_line(line: str) -> str:
    line = rebase_local_include_line(line)
    line = EXPORT_PREFIX_RE.sub(lambda match: match.group("indent"), line, count=1)
    return BARE_NULLPTR_T_RE.sub("std::nullptr_t", line)


def header_collision_rewrite(line: str, unit: ModuleUnit) -> str:
    prefixes = {
        "conflux.json": "ConfluxJson",
        "conflux.net.response_cache": "ConfluxResponseCache",
    }
    prefix = prefixes.get(unit.module_name)
    if unit.module_name == "conflux.socket_io":
        return re.sub(r"\bFdGuard\b", "ConfluxSocketIoFdGuard", line)
    if prefix is None:
        return line
    line = re.sub(r"\bTransparentStringHash\b", f"{prefix}TransparentStringHash", line)
    line = re.sub(r"\bTransparentStringEqual\b", f"{prefix}TransparentStringEqual", line)
    return line

def std_guard_block(headers: Iterable[str], compat: bool) -> list[str]:
    macro = "CONFLUX_HEADER_USE_IMPORT_STD_COMPAT" if compat else "CONFLUX_HEADER_USE_IMPORT_STD"
    import_name = "std.compat" if compat else "std"
    out = [f"#if defined({macro}) && {macro}\n", f"import {import_name};\n", "#else\n"]
    for header in headers:
        out.append(f"#include <{header}>\n")
    out.append("#endif\n")
    return out


def import_guard_block(import_name: str, exported: bool, for_header: bool, owner_module: str | None = None) -> list[str]:
    include = import_to_include(import_name, owner_module)
    if include is None:
        prefix = "export " if exported and not for_header else ""
        return [f"{prefix}import {import_name};\n"]
    if for_header:
        return [
            "#if defined(CONFLUX_HEADER_USE_MODULE_IMPORTS) && CONFLUX_HEADER_USE_MODULE_IMPORTS\n",
            f"import {import_name};\n",
            "#else\n",
            f"#include <{include}>\n",
            "#endif\n",
        ]
    prefix = "export " if exported else ""
    return [
        "#if defined(CONFLUX_MODULE_REEXPORT_IMPORTS) && CONFLUX_MODULE_REEXPORT_IMPORTS\n" if exported else "#if defined(CONFLUX_MODULE_USE_IMPORTS) && CONFLUX_MODULE_USE_IMPORTS\n",
        f"{prefix}import {import_name};\n",
        "#endif\n",
    ]


def transform_to_header(unit: ModuleUnit) -> tuple[str, list[str]]:
    warnings: list[str] = []
    before_decl = list(unit.lines[: unit.declaration_index])
    after_decl = list(unit.lines[unit.declaration_index + 1 :])
    body_text = "".join(after_decl)
    before_std_headers: set[str] = set()
    before_compat_headers: set[str] = set()
    before_non_std_lines: list[str] = []
    for line in before_decl:
        if line.strip() == "module;":
            continue
        header = angle_include_header(line)
        if header is not None and is_known_std_header(header):
            before_std_headers.add(header)
            continue
        before_non_std_lines.append(rebase_local_include_line(line))
    if re.search(r"\bassert\s*\(", body_text) and "#include <cassert>\n" not in before_non_std_lines:
        before_non_std_lines.append("#include <cassert>\n")
    std_headers = sorted(set(infer_standard_headers(body_text, uses_std_compat=False)) | before_std_headers)
    compat_headers = sorted(set(infer_standard_headers(body_text, uses_std_compat=True)) | before_compat_headers)

    out: list[str] = [
        "#pragma once\n",
        f"{GENERATED_BANNER}\n",
        f"#include <{CONFIG_HEADER_RELPATH.as_posix()}>\n",
        "\n",
    ]
    saw_std = False
    saw_std_compat = False
    if std_headers:
        out.extend(std_guard_block(std_headers, compat=False))
        saw_std = True
    if compat_headers:
        out.extend(std_guard_block(compat_headers, compat=True))
        saw_std_compat = True
    if std_headers or compat_headers:
        out.append("\n")

    # Preserve non-standard GMF includes/extern declarations from the source,
    # except the bare module; marker. They are real header dependencies in
    # compatibility mode.
    out.extend(before_non_std_lines)
    if before_non_std_lines:
        out.append("\n")

    for index, line in enumerate(after_decl):
        match = IMPORT_RE.match(line)
        if match is not None:
            name = match.group("name")
            if name == "std":
                if not saw_std:
                    out.extend(std_guard_block(std_headers, compat=False))
                    saw_std = True
                continue
            if name == "std.compat":
                if not saw_std_compat:
                    out.extend(std_guard_block(compat_headers, compat=True))
                    saw_std_compat = True
                continue
            out.extend(import_guard_block(name, exported=bool(match.group("export")), for_header=True, owner_module=unit.module_name))
            continue
        rewritten = header_collision_rewrite(line, unit)
        out.append(headerize_source_line(rewritten, force_inline=starts_multiline_function_definition(after_decl, index)))

    symbols, symbol_warnings = parse_export_symbols(tuple(after_decl))
    warnings.extend(symbol_warnings)
    stream_tokens = find_std_stream_tokens(body_text, explicit_std_headers(before_decl))
    if stream_tokens:
        warnings.append("std stream tokens intentionally not inferred: " + ", ".join(stream_tokens))

    if not saw_std and unit.uses_std:
        warnings.append("unit marked uses_std but no import std line was transformed")
    if not saw_std_compat and unit.uses_std_compat:
        warnings.append("unit marked uses_std_compat but no import std.compat line was transformed")
    return "".join(out), warnings

def brace_delta(line: str) -> int:
    # This intentionally ignores comments/strings; good enough for export namespace
    # discovery and avoids pretending to be a C++ parser.
    return line.count("{") - line.count("}")


def namespace_is_detail(namespace: str | None) -> bool:
    if namespace is None:
        return False
    return any(part == "detail" or part.endswith("_detail") for part in namespace.split("::"))


CXX_RESERVED_WORDS = {
    "alignas", "alignof", "and", "and_eq", "asm", "auto", "bitand", "bitor",
    "bool", "break", "case", "catch", "char", "char8_t", "char16_t", "char32_t",
    "class", "compl", "concept", "const", "consteval", "constexpr", "constinit",
    "const_cast", "continue", "co_await", "co_return", "co_yield", "decltype",
    "default", "delete", "do", "double", "dynamic_cast", "else", "enum",
    "explicit", "export", "extern", "false", "float", "for", "friend", "goto",
    "if", "inline", "int", "long", "mutable", "namespace", "new", "noexcept",
    "not", "not_eq", "nullptr", "operator", "or", "or_eq", "private", "protected",
    "public", "register", "reinterpret_cast", "requires", "return", "short",
    "signed", "sizeof", "static", "static_assert", "static_cast", "struct",
    "switch", "template", "this", "thread_local", "throw", "true", "try",
    "typedef", "typeid", "typename", "union", "unsigned", "using", "virtual",
    "void", "volatile", "wchar_t", "while", "xor", "xor_eq",
}


def symbol_is_exportable_name(name: str) -> bool:
    return name not in CXX_RESERVED_WORDS


def symbol_is_probably_template_param(name: str) -> bool:
    return bool(re.fullmatch(r"[A-Z](?:[A-Z0-9_]{0,2})", name)) or name in {
        "T", "U", "V", "F", "M", "R", "H", "Cb", "Owner", "Driver", "Body", "Handler",
    }


def strip_template_prefixes(text: str) -> str:
    out = re.sub(r"\bexport\s+template\s*<[^>]*>\s*", "export ", text, flags=re.DOTALL)
    out = re.sub(r"\btemplate\s*<[^>]*>\s*", "", out, flags=re.DOTALL)
    # Drop requires clauses; they often contain function-call-like text and nested braces.
    out = re.sub(r"\brequires\s+requires\s*\([^)]*\)\s*\{.*?\}\s*", " ", out, flags=re.DOTALL)
    out = re.sub(r"\brequires\s+requires\s*\([^)]*\)\s*\{.*?\n(?=\s*(?:\[\[|auto\b|[A-Za-z_:][A-Za-z0-9_:<>\s,&*]*\s+[A-Za-z_~][A-Za-z0-9_:~]*\s*\())", " ", out, flags=re.DOTALL)
    out = re.sub(r"^\s*(?:export\s+)?requires\s*(?:\([^)]*\)|[^\n]+)\s*", "export ", out, flags=re.DOTALL)
    return out


def normalize_decl_text(text: str) -> str:
    text = "\n".join(part.split("//", 1)[0] for part in text.splitlines())
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.DOTALL)
    return re.sub(r"\s+", " ", text).strip()


def extract_symbol_from_decl(text: str, current_namespace: str | None) -> str | None:
    decl = normalize_decl_text(strip_template_prefixes(text))
    if not decl:
        return None
    decl = re.sub(r"^(?:export\s+)?(?:\[\[[^\]]+\]\]\s*)+", "export ", decl)
    decl = re.sub(r"\s+(?:requires)\s+.*?(?=\{|;|$)", " ", decl)
    patterns = (
        r"\bconcept\s+([A-Za-z_][A-Za-z0-9_]*)\b",
        r"\b(?:class|struct|union)\s+([A-Za-z_][A-Za-z0-9_]*)\b",
        r"\benum\s+(?:class\s+)?([A-Za-z_][A-Za-z0-9_]*)\b",
        r"\busing\s+([A-Za-z_][A-Za-z0-9_]*)\b",
    )
    for pattern in patterns:
        match = re.search(pattern, decl)
        if match is not None:
            return match.group(1)

    # Function-like declarations/definitions. Pick the last viable name before
    # an opening paren before the first body/semicolon; this skips requires(...)
    # and attribute internals while still handling multiline signatures.
    head = re.split(r"[;{]", decl, maxsplit=1)[0]
    candidates = re.findall(r"([A-Za-z_~][A-Za-z0-9_:~]*)\s*\(", head)
    skip = {
        "requires", "decltype", "sizeof", "noexcept", "static_cast", "reinterpret_cast",
        "const_cast", "dynamic_cast", "std::same_as", "std::convertible_to",
    }
    for candidate in reversed(candidates):
        if candidate in skip or candidate.startswith("std::"):
            continue
        name = candidate.rsplit("::", 1)[-1]
        if name and name not in {"operator", "requires"}:
            return name

    # Variable / inline constant. Keep this last so return types do not win.
    var_match = re.search(
        r"\b(?:inline\s+)?(?:constexpr\s+|constinit\s+|const\s+)*[A-Za-z_:][A-Za-z0-9_:<>\s,&*]*\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?:=|\{|;)",
        decl,
    )
    if var_match is not None:
        return var_match.group(1)
    return None



def has_real_function_candidate(text: str) -> bool:
    candidates = re.findall(r"([A-Za-z_~][A-Za-z0-9_:~]*)\s*\(", normalize_decl_text(text))
    skip = {
        "requires", "decltype", "sizeof", "noexcept", "static_cast", "reinterpret_cast",
        "const_cast", "dynamic_cast", "std::same_as", "std::convertible_to",
    }
    return any(c.rsplit("::", 1)[-1] not in skip and not c.startswith("std::") for c in candidates)

def declaration_complete(text: str) -> bool:
    # Good enough for exported API discovery: stop at the first top-level-ish
    # semicolon, or a real function-definition brace. Requires-expressions also
    # contain braces, so a brace is only terminal after a viable function name.
    paren = 0
    angle = 0
    skip_names = {
        "requires", "decltype", "sizeof", "noexcept", "static_cast", "reinterpret_cast",
        "const_cast", "dynamic_cast",
    }
    for index, ch in enumerate(text):
        if ch == "(":
            paren += 1
        elif ch == ")" and paren:
            paren -= 1
        elif ch == "<":
            angle += 1
        elif ch == ">" and angle:
            angle -= 1
        elif ch == ";" and paren == 0:
            if "requires requires" in text[:index] and not has_real_function_candidate(text):
                continue
            return True
        elif ch == "{" and paren == 0:
            if "requires requires" in text[:index]:
                continue
            prefix = normalize_decl_text(text[:index])
            candidates = re.findall(r"([A-Za-z_~][A-Za-z0-9_:~]*)\s*\(", prefix)
            if any(c.rsplit("::", 1)[-1] not in skip_names and not c.startswith("std::") for c in candidates):
                return True
    return False

def parse_export_symbols(lines: tuple[str, ...]) -> tuple[list[ExportSymbol], list[str]]:
    symbols: list[ExportSymbol] = []
    warnings: list[str] = []
    namespace_stack: list[tuple[str, int, bool]] = []
    depth = 0
    pending_decl: list[str] = []
    pending_namespace: str | None = None
    pending_explicit = False

    def current_namespace_name(raw_name: str) -> str:
        if "::" in raw_name or not namespace_stack:
            return raw_name
        return f"{namespace_stack[-1][0]}::{raw_name}"

    def flush_pending() -> None:
        nonlocal pending_decl, pending_namespace, pending_explicit
        if not pending_decl:
            return
        text = "".join(pending_decl)
        symbol = extract_symbol_from_decl(text, pending_namespace)
        if symbol is None:
            if pending_explicit:
                sample = " ".join(x.strip() for x in pending_decl if x.strip())[:120]
                warnings.append(f"could not infer exported declaration near: {sample}")
        elif symbol_is_exportable_name(symbol) and not symbol_is_probably_template_param(symbol) and symbol != "detail":
            if not namespace_is_detail(pending_namespace):
                symbols.append(ExportSymbol(pending_namespace, symbol))
        pending_decl = []
        pending_namespace = None
        pending_explicit = False

    for raw in lines:
        line = raw.rstrip("\n")
        stripped = line.lstrip()

        namespace_match = NAMESPACE_RE.match(line)
        is_namespace_open = namespace_match is not None
        if is_namespace_open:
            flush_pending()
            ns_name = current_namespace_name(namespace_match.group("name"))
            namespace_stack.append((ns_name, depth + brace_delta(line), stripped.startswith("export namespace")))
            depth += brace_delta(line)
            continue

        current_namespace = namespace_stack[-1][0] if namespace_stack else None
        in_export_namespace = any(item[2] for item in namespace_stack)
        declaration_depth_ok = depth == (namespace_stack[-1][1] if namespace_stack else 0)

        starts_export = stripped.startswith("export ") and not stripped.startswith("export import ")
        starts_implicit_export = in_export_namespace and declaration_depth_ok and stripped and not stripped.startswith(("//", "#", "}", "private:", "public:", "protected:"))
        starts_decl = starts_export or starts_implicit_export

        if pending_decl:
            pending_decl.append(line + "\n")
            if declaration_complete("".join(pending_decl)):
                flush_pending()
        elif starts_decl:
            pending_decl = [line + "\n"]
            pending_namespace = current_namespace
            pending_explicit = starts_export
            if declaration_complete(line):
                flush_pending()

        depth += brace_delta(line)
        while namespace_stack and depth < namespace_stack[-1][1]:
            flush_pending()
            namespace_stack.pop()

    flush_pending()

    unique: list[ExportSymbol] = []
    seen: set[tuple[str | None, str]] = set()
    for symbol in symbols:
        if namespace_is_detail(symbol.namespace) or symbol.name == "detail" or symbol.name.endswith("_detail"):
            continue
        key = (symbol.namespace, symbol.name)
        if key not in seen:
            unique.append(symbol)
            seen.add(key)
    return unique, warnings

def wrapper_import_prelude(unit: ModuleUnit) -> list[str]:
    out: list[str] = []
    seen_std = False
    seen_std_compat = False
    in_import_prelude = True
    for line in unit.lines[unit.declaration_index + 1 :]:
        stripped = line.strip()
        match = IMPORT_RE.match(line)
        if match is not None:
            name = match.group("name")
            is_export = bool(match.group("export"))
            if name == "std":
                if not seen_std:
                    out.extend([
                        "#if defined(CONFLUX_MODULE_USE_IMPORT_STD) && CONFLUX_MODULE_USE_IMPORT_STD\n",
                        "import std;\n",
                        "#endif\n",
                    ])
                    seen_std = True
            elif name == "std.compat":
                if not seen_std_compat:
                    out.extend([
                        "#if defined(CONFLUX_MODULE_USE_IMPORT_STD_COMPAT) && CONFLUX_MODULE_USE_IMPORT_STD_COMPAT\n",
                        "import std.compat;\n",
                        "#endif\n",
                    ])
                    seen_std_compat = True
            elif is_export:
                out.extend(import_guard_block(name, exported=True, for_header=False, owner_module=unit.module_name))
            # Plain imports are satisfied by the GMF header include.
            continue
        if stripped.startswith("#") or stripped.startswith("//") or stripped == "":
            if in_import_prelude:
                out.append(line)
            continue
        break
    # Trim trailing vertical whitespace from copied NOLINT/preprocessor prelude.
    while out and out[-1].strip() == "":
        out.pop()
    if out:
        out.append("\n")
    return out


def transform_to_module_wrapper(unit: ModuleUnit, header_relpath: Path) -> tuple[str, list[str]]:
    symbols, warnings = parse_export_symbols(unit.lines[unit.declaration_index + 1 :])
    out: list[str] = [
        "module;\n",
        f"#include <{header_relpath.as_posix()}>\n",
        "\n",
        f"export module {unit.module_name};\n",
    ]
    out.extend(wrapper_import_prelude(unit))
    out.append(f"{GENERATED_BANNER}\n")
    if symbols:
        by_namespace: dict[str | None, list[str]] = {}
        for symbol in symbols:
            by_namespace.setdefault(symbol.namespace, []).append(symbol.name)
        for namespace, names in sorted((k, v) for k, v in by_namespace.items() if k is not None):
            out.append(f"export namespace {namespace} {{\n")
            for name in names:
                out.append(f"    using ::{namespace}::{name};\n")
            out.append("}\n")
    else:
        if unit.export_imports:
            out.append("// Aggregator module: exported imports are preserved by the wrapper prelude.\n")
        else:
            out.append("// No exported declarations inferred from source; header include carries declarations if any.\n")
    return "".join(out), warnings



def collect_config_macros(src_root: Path) -> list[str]:
    macros: set[str] = {
        "CONFLUX_ENABLE_RECV_BUNDLE",
        "CONFLUX_ENABLE_RECV_INCREMENTAL_BUF",
        "CONFLUX_ENABLE_SEND_ZC",
        "CONFLUX_ENABLE_RING_GROWTH",
        "CONFLUX_ENABLE_IOPOLL_STORAGE_TEST",
        "CONFLUX_HEADER_USE_IMPORT_STD",
        "CONFLUX_HEADER_USE_IMPORT_STD_COMPAT",
        "CONFLUX_HEADER_USE_MODULE_IMPORTS",
        "CONFLUX_MODULE_USE_IMPORT_STD",
        "CONFLUX_MODULE_USE_IMPORT_STD_COMPAT",
        "CONFLUX_MODULE_USE_IMPORTS",
        "CONFLUX_MODULE_REEXPORT_IMPORTS",
        "CONFLUX_RUNTIME_HAS_IOU_PBUF_RING_INC",
        "CONFLUX_RUNTIME_HAS_IO_URING_RESIZE_RINGS",
        "CONFLUX_RUNTIME_HAS_IO_URING_CLONE_BUFFERS",
        "CONFLUX_HAS_BROTLI",
        "CONFLUX_HAS_COMPRESS",
        "CONFLUX_HAS_DB",
        "CONFLUX_HAS_FILE_WATCH",
        "CONFLUX_HAS_HTTP2",
        "CONFLUX_HAS_HTTP3",
        "CONFLUX_HAS_ISAL",
        "CONFLUX_HAS_JSON",
        "CONFLUX_HAS_LIBDEFLATE",
        "CONFLUX_HAS_METRICS",
        "CONFLUX_HAS_TEMPLATES",
        "CONFLUX_HAS_TEMPLATES_WATCH",
        "CONFLUX_HAS_TLS",
        "CONFLUX_HAS_ZLIB",
        "CONFLUX_HAS_ZLIB_NG",
        "CONFLUX_HAS_ZSTD",
    }
    for suffix in ("*.c", "*.cc", "*.cpp", "*.cxx", "*.h", "*.hh", "*.hpp", "*.hxx"):
        for path in src_root.rglob(suffix):
            try:
                text = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                text = path.read_text(errors="ignore")
            for line in text.splitlines():
                match = DIRECT_IF_MACRO_RE.match(line)
                if match is not None:
                    macros.add(match.group(1))
    return sorted(macros)


def render_config_header(macros: Iterable[str]) -> str:
    out: list[str] = [
        "#pragma once\n",
        f"{GENERATED_BANNER}\n",
        "// Fallback feature/configuration macros for generated header mode.\n",
        "// Build systems may define any of these before including conflux headers.\n",
        "\n",
        "#ifndef CONFLUX_API_SURFACE_CURATED\n",
        "#define CONFLUX_API_SURFACE_CURATED 1\n",
        "#endif\n",
        "#ifndef CONFLUX_API_SURFACE_EXTENDED\n",
        "#define CONFLUX_API_SURFACE_EXTENDED 2\n",
        "#endif\n",
        "#ifndef CONFLUX_API_SURFACE_COMPLETE\n",
        "#define CONFLUX_API_SURFACE_COMPLETE 3\n",
        "#endif\n",
        "#ifndef CONFLUX_API_SURFACE_LEVEL\n",
        "#define CONFLUX_API_SURFACE_LEVEL CONFLUX_API_SURFACE_CURATED\n",
        "#endif\n",
        "#ifndef CONFLUX_BUILD_API_SURFACE\n",
        "#define CONFLUX_BUILD_API_SURFACE \"curated\"\n",
        "#endif\n",
        "\n",
    ]
    skip = {
        "CONFLUX_API_SURFACE_CURATED",
        "CONFLUX_API_SURFACE_EXTENDED",
        "CONFLUX_API_SURFACE_COMPLETE",
        "CONFLUX_API_SURFACE_LEVEL",
        "CONFLUX_BUILD_API_SURFACE",
    }
    for macro in macros:
        if macro in skip:
            continue
        out.extend([
            f"#ifndef {macro}\n",
            f"#define {macro} 0\n",
            "#endif\n",
        ])
    return "".join(out)


def render_features_header() -> str:
    features = [
        ("HAS_TLS", "CONFLUX_HAS_TLS"),
        ("HAS_COMPRESS", "CONFLUX_HAS_COMPRESS"),
        ("HAS_ZLIB", "CONFLUX_HAS_ZLIB"),
        ("HAS_LIBDEFLATE", "CONFLUX_HAS_LIBDEFLATE"),
        ("HAS_ZLIB_NG", "CONFLUX_HAS_ZLIB_NG"),
        ("HAS_ISAL", "CONFLUX_HAS_ISAL"),
        ("HAS_BROTLI", "CONFLUX_HAS_BROTLI"),
        ("HAS_ZSTD", "CONFLUX_HAS_ZSTD"),
        ("HAS_JSON", "CONFLUX_HAS_JSON"),
        ("HAS_FILE_WATCH", "CONFLUX_HAS_FILE_WATCH"),
        ("HAS_TEMPLATES", "CONFLUX_HAS_TEMPLATES"),
        ("HAS_TEMPLATES_WATCH", "CONFLUX_HAS_TEMPLATES_WATCH"),
        ("HAS_METRICS", "CONFLUX_HAS_METRICS"),
        ("HAS_HTTP2", "CONFLUX_HAS_HTTP2"),
        ("HAS_HTTP3", "CONFLUX_HAS_HTTP3"),
        ("HAS_DB", "CONFLUX_HAS_DB"),
    ]
    out: list[str] = [
        "#pragma once\n",
        f"{GENERATED_BANNER}\n",
        f"#include <{CONFIG_HEADER_RELPATH.as_posix()}>\n",
        "\n",
        "namespace conflux {\n",
        "inline constexpr char const *API_SURFACE = CONFLUX_BUILD_API_SURFACE;\n",
        "inline constexpr int API_SURFACE_LEVEL = CONFLUX_API_SURFACE_LEVEL;\n",
    ]
    for name, macro in features:
        out.append(f"inline constexpr bool {name} = {macro};\n")
    out.append("} // namespace conflux\n")
    return "".join(out)


def resolve_local_include(src_root: Path, owner: Path, include_name: str) -> Path | None:
    rel = Path(include_name)
    candidates = [owner.parent / rel, src_root / rel, src_root / rel.name]
    for candidate in candidates:
        if candidate.exists() and candidate.is_file():
            return candidate
    return None


def collect_local_includes_from_text(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines(keepends=True):
        match = LOCAL_INCLUDE_RE.match(line)
        if match is not None:
            inc = match.group("path")
            rel = Path(inc)
            if not rel.is_absolute() and ".." not in rel.parts:
                out.append(inc)
    return out


def emit_private_include_headers(
    src_root: Path,
    include_out: Path,
    units: Iterable[ModuleUnit],
    write: bool,
    consumer_roots: Iterable[Path] = (),
) -> tuple[int, list[dict[str, str]]]:
    queue: list[tuple[Path, str]] = []
    for unit in units:
        for line in unit.lines:
            match = LOCAL_INCLUDE_RE.match(line)
            if match is not None:
                queue.append((unit.path, match.group("path")))
    for root in consumer_roots:
        if not root.exists():
            continue
        for path in sorted(root.rglob("*")):
            if not path.is_file():
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            for include_name in collect_local_includes_from_text(text):
                queue.append((path, include_name))

    changed = 0
    emitted: list[dict[str, str]] = []
    seen: set[Path] = set()
    while queue:
        owner, include_name = queue.pop(0)
        source = resolve_local_include(src_root, owner, include_name)
        if source is None or source in seen:
            continue
        seen.add(source)
        rel = Path(include_name)
        target_rel = PRIVATE_INCLUDE_PREFIX / rel
        target = include_out / target_rel
        text = source.read_text(encoding="utf-8")
        for nested in collect_local_includes_from_text(text):
            queue.append((source, nested))
        transformed = "".join(rebase_local_include_line(line) for line in text.splitlines(keepends=True))
        content = f"{GENERATED_BANNER}\n" + transformed
        if write_if_changed(target, content, write):
            changed += 1
        try:
            source_label = str(source.relative_to(src_root))
        except ValueError:
            source_label = str(source)
        emitted.append({"source": source_label, "header": str(target), "include": target_rel.as_posix()})
    return changed, emitted

def write_if_changed(path: Path, content: str, write: bool) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    if write:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return True



def header_source_include_line(unit: ModuleUnit, name: str) -> list[str]:
    if name in {"std", "std.compat"}:
        return []
    include = import_to_include(name, unit.module_name)
    if include is not None:
        return [f"#include <{include}>\n"]
    return [f"import {name};\n"]


def header_source_import_prelude(unit: ModuleUnit, lines: list[str]) -> tuple[list[str], list[str]]:
    out: list[str] = []
    body_start = 0
    for index, line in enumerate(lines):
        stripped = line.strip()
        match = IMPORT_RE.match(line)
        if match is not None:
            out.extend(header_source_include_line(unit, match.group("name")))
            body_start = index + 1
            continue
        if stripped.startswith("#") or stripped.startswith("//") or stripped == "":
            out.append(line)
            body_start = index + 1
            continue
        break
    while out and out[-1].strip() == "":
        out.pop()
    if out:
        out.append("\n")
    return out, lines[body_start:]


def module_source_import_prelude(lines: list[str]) -> tuple[list[str], list[str]]:
    out: list[str] = []
    body_start = 0
    for index, line in enumerate(lines):
        stripped = line.strip()
        match = IMPORT_RE.match(line)
        if match is not None:
            name = match.group("name")
            if name not in {"std", "std.compat"}:
                out.append(line)
            body_start = index + 1
            continue
        if stripped.startswith("#") or stripped.startswith("//") or stripped == "":
            out.append(line)
            body_start = index + 1
            continue
        break
    while out and out[-1].strip() == "":
        out.pop()
    if out:
        out.append("\n")
    return out, lines[body_start:]


def source_standard_include_block(unit: ModuleUnit, text: str, include_own_header: bool) -> list[str]:
    out: list[str] = [f"#include <{CONFIG_HEADER_RELPATH.as_posix()}>\n"]
    headers = set(infer_standard_headers(text, uses_std_compat=unit.uses_std_compat))
    for token in set(STD_TOKEN_RE.findall(text)) & STD_STREAM_TOKENS:
        headers.add(STREAM_TOKEN_HEADER[token])
    if "std::println" in text or "std::print" in text:
        headers.add("print")
    for header in sorted(headers):
        out.append(f"#include <{header}>\n")
    if include_own_header:
        own_header = module_to_header_relpath(unit.module_name.split(":", 1)[0]).as_posix()
        if f"#include <{own_header}>\n" not in out:
            out.append(f"#include <{own_header}>\n")
    return out


def transform_to_module_no_import_source(unit: ModuleUnit) -> str:
    before_decl = list(unit.lines[: unit.declaration_index])
    after_decl = list(unit.lines[unit.declaration_index + 1 :])
    import_prelude, body = module_source_import_prelude(after_decl)
    out: list[str] = ["module;\n", f"{GENERATED_BANNER}\n"]
    for line in before_decl:
        if line.strip() == "module;":
            continue
        out.append(rebase_local_include_line(line))
    out.extend(source_standard_include_block(unit, "".join(after_decl), include_own_header=False))
    out.append("\n")
    export_prefix = "export " if unit.is_interface else ""
    out.append(f"{export_prefix}module {unit.module_name};\n")
    out.extend(import_prelude)
    out.append("\n")
    out.extend(module_overlay_source_line(line) for line in body)
    return "".join(out)


def transform_to_header_mode_source(unit: ModuleUnit, include_own_header: bool = True) -> str:
    before_decl = list(unit.lines[: unit.declaration_index])
    after_decl = list(unit.lines[unit.declaration_index + 1 :])
    import_prelude, body = header_source_import_prelude(unit, after_decl)
    out: list[str] = [f"{GENERATED_BANNER}\n"]
    for line in before_decl:
        if line.strip() == "module;":
            continue
        out.append(rebase_local_include_line(line))
    out.extend(source_standard_include_block(unit, "".join(after_decl), include_own_header=include_own_header))
    out.extend(import_prelude)
    out.append("\n")
    out.extend(header_impl_source_line(header_collision_rewrite(line, unit)) for line in body)
    return "".join(out)


def transform_to_module_no_import_consumer(path: Path) -> str:
    lines = read_lines(path)
    text = "".join(lines)
    stream_headers: set[str] = set()
    if any(token in text for token in ("std::ifstream", "std::ofstream", "std::fstream")):
        stream_headers.add("fstream")
    if any(token in text for token in ("std::istringstream", "std::ostringstream", "std::stringstream")):
        stream_headers.add("sstream")
    if any(token in text for token in ("std::cerr", "std::cout", "std::clog", "std::cin")):
        stream_headers.add("iostream")
    out: list[str] = [
        f"{GENERATED_BANNER}\n",
        f"#include <{CONFIG_HEADER_RELPATH.as_posix()}>\n",
    ]
    for header in sorted(set(infer_standard_headers(text, uses_std_compat="import std.compat;" in text)) | stream_headers):
        out.append(f"#include <{header}>\n")
    if "std::println" in text or "std::print" in text:
        out.append("#include <print>\n")
    out.append("\n")
    for line in lines:
        if line.strip() == "module;" or MODULE_DECL_RE.match(line):
            continue
        match = IMPORT_RE.match(line)
        if match is not None and match.group("name") in {"std", "std.compat"}:
            continue
        out.append(rebase_local_include_line(line))
    return "".join(out)


def transform_to_header_mode_consumer(path: Path, local_imports: dict[str, str] | None = None) -> str:
    local_imports = local_imports or {}
    lines = read_lines(path)
    text = "".join(lines)
    stream_headers: set[str] = set()
    if any(token in text for token in ("std::ifstream", "std::ofstream", "std::fstream")):
        stream_headers.add("fstream")
    if any(token in text for token in ("std::istringstream", "std::ostringstream", "std::stringstream")):
        stream_headers.add("sstream")
    if any(token in text for token in ("std::cerr", "std::cout", "std::clog", "std::cin")):
        stream_headers.add("iostream")
    out: list[str] = [
        f"{GENERATED_BANNER}\n",
        f"#include <{CONFIG_HEADER_RELPATH.as_posix()}>\n",
    ]
    for header in sorted(set(infer_standard_headers(text, uses_std_compat=False)) | stream_headers):
        out.append(f"#include <{header}>\n")
    if "std::println" in text or "std::print" in text:
        out.append("#include <print>\n")
    out.append("\n")
    for line in lines:
        if line.strip() == "module;" or MODULE_DECL_RE.match(line):
            continue
        match = IMPORT_RE.match(line)
        if match is not None:
            name = match.group("name")
            if name in {"std", "std.compat"}:
                continue
            include = local_imports.get(name) or import_to_include(name)
            if include is not None:
                out.append(f"#include <{include}>\n")
            else:
                out.append(line)
            continue
        out.append(EXPORT_PREFIX_RE.sub(lambda match: match.group("indent"), rebase_local_include_line(line), count=1))
    return "".join(out)


def transform_to_header_mode_consumer_header(path: Path, local_imports: dict[str, str]) -> str:
    lines = read_lines(path)
    text = "".join(lines)
    stream_headers: set[str] = set()
    if any(token in text for token in ("std::ifstream", "std::ofstream", "std::fstream")):
        stream_headers.add("fstream")
    if any(token in text for token in ("std::istringstream", "std::ostringstream", "std::stringstream")):
        stream_headers.add("sstream")
    if any(token in text for token in ("std::cerr", "std::cout", "std::clog", "std::cin")):
        stream_headers.add("iostream")
    out: list[str] = [
        "#pragma once\n",
        f"{GENERATED_BANNER}\n",
        f"#include <{CONFIG_HEADER_RELPATH.as_posix()}>\n",
    ]
    for header in sorted(set(infer_standard_headers(text, uses_std_compat=False)) | stream_headers):
        out.append(f"#include <{header}>\n")
    if "std::println" in text or "std::print" in text:
        out.append("#include <print>\n")
    out.append("\n")
    for index, line in enumerate(lines):
        if line.strip() == "module;" or MODULE_DECL_RE.match(line):
            continue
        match = IMPORT_RE.match(line)
        if match is not None:
            name = match.group("name")
            if name in {"std", "std.compat"}:
                continue
            include = local_imports.get(name) or import_to_include(name)
            if include is not None:
                out.append(f"#include <{include}>\n")
            else:
                out.append(line)
            continue
        out.append(headerize_source_line(rebase_local_include_line(line), force_inline=starts_multiline_function_definition(lines, index)))
    return "".join(out)


def consumer_module_name(path: Path) -> str | None:
    for line in read_lines(path):
        match = MODULE_DECL_RE.match(line)
        if match is not None:
            return match.group("name")
    return None


def emit_consumer_overlay(consumer_root: Path, consumer_out: Path, include_out: Path, write: bool, mode: str = "header") -> tuple[int, list[dict[str, str]]]:
    changed = 0
    emitted: list[dict[str, str]] = []
    if not consumer_root.exists():
        return changed, emitted
    local_imports: dict[str, str] = {}
    for path in sorted(consumer_root.rglob("*.cxx")):
        name = consumer_module_name(path)
        if name is not None:
            local_imports[name] = module_to_header_relpath(name).as_posix()
    for path in sorted(consumer_root.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(consumer_root)
        out_path = consumer_out / rel
        if path.suffix == ".cxx":
            if mode == "module-std-headers":
                unit = discover_module_unit(path, consumer_root)
                if unit is not None:
                    out_content = transform_to_module_no_import_source(unit)
                    emit_mode = "module-consumer-module-no-import-std"
                else:
                    out_content = transform_to_module_no_import_consumer(path)
                    emit_mode = "module-consumer-no-import-std"
            elif mode == "header":
                out_content = transform_to_header_mode_consumer(path, local_imports)
                emit_mode = "header-consumer"
                name = local_imports.get(consumer_module_name(path) or "")
                if name is not None:
                    header_path = include_out / name
                    header_content = transform_to_header_mode_consumer_header(path, local_imports)
                    if write_if_changed(header_path, header_content, write):
                        changed += 1
                    emitted.append({"source": str(rel), "output": str(header_path), "mode": "header-consumer-local-module"})
            else:
                raise ValueError(f"unknown consumer overlay mode: {mode}")
        else:
            try:
                out_content = path.read_text(encoding="utf-8")
                emit_mode = "copied"
            except UnicodeDecodeError:
                if write:
                    out_path.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(path, out_path)
                emitted.append({"source": str(rel), "output": str(out_path), "mode": "copied-binary"})
                continue
        if write_if_changed(out_path, out_content, write):
            changed += 1
        emitted.append({"source": str(rel), "output": str(out_path), "mode": emit_mode})
    return changed, emitted


def emit_source_overlay(src_root: Path, source_out: Path, units: Iterable[ModuleUnit], mode: str, write: bool) -> tuple[int, list[dict[str, str]]]:
    unit_by_path = {u.path.resolve(): u for u in units}
    changed = 0
    emitted: list[dict[str, str]] = []
    for path in sorted(src_root.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(src_root)
        out_path = source_out / rel
        unit = unit_by_path.get(path.resolve())
        if unit is None:
            try:
                content = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                if write:
                    out_path.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(path, out_path)
                emitted.append({"source": str(rel), "output": str(out_path), "mode": "copied-binary"})
                continue
            out_content = content
            emit_mode = "copied"
        elif mode == "module-std-headers":
            if unit.is_interface:
                out_content = transform_to_module_no_import_source(unit)
                emit_mode = "module-interface-no-import-std"
            else:
                out_content = transform_to_module_no_import_source(unit)
                emit_mode = "module-impl-no-import-std"
        elif mode == "header":
            if unit.is_partition:
                out_content = transform_to_header_mode_source(unit, include_own_header=False)
                emit_mode = "header-impl-partition"
            elif unit.is_interface:
                out_content = f"{GENERATED_BANNER}\n// Header-mode public declarations live in <{module_to_header_relpath(unit.module_name).as_posix()}>.\n"
                emit_mode = "header-interface-stub"
            else:
                out_content = transform_to_header_mode_source(unit)
                emit_mode = "header-impl"
        else:
            raise ValueError(f"unknown source overlay mode: {mode}")
        if write_if_changed(out_path, out_content, write):
            changed += 1
        item = {"source": str(rel), "output": str(out_path), "mode": emit_mode}
        if unit is not None:
            item["module"] = unit.module_name
        emitted.append(item)
    return changed, emitted


def cmake_quote(value: str) -> str:
    return '"' + value.replace('\\', '/').replace('"', '\\"') + '"'


def render_cmake_fragment(manifest: dict[str, object]) -> str:
    header_impl_sources: list[str] = []
    header_impl_modules: dict[str, str] = {}
    source_overlay = manifest.get("source_overlay")
    if isinstance(source_overlay, dict):
        files = source_overlay.get("files")
        if isinstance(files, list):
            for item in files:
                if isinstance(item, dict) and str(item.get("mode", "")).startswith("header-impl"):
                    output = item.get("output")
                    module = item.get("module")
                    if isinstance(output, str):
                        header_impl_sources.append(output)
                        if isinstance(module, str):
                            header_impl_modules[output] = module

    lines = [
        "# Generated by scripts/module_header_bridge.py; do not edit by hand.",
        "",
        "set(CONFLUX_BRIDGE_HEADER_IMPL_SOURCES",
    ]
    lines.extend(f"    {cmake_quote(path)}" for path in sorted(header_impl_sources))
    lines.extend([
        ")",
        "set(CONFLUX_BRIDGE_HEADER_IMPL_MODULES",
    ])
    lines.extend(f"    {cmake_quote(header_impl_modules.get(path, ''))}" for path in sorted(header_impl_sources))
    lines.extend([
        ")",
        "",
        "if(CONFLUX_BRIDGE_HEADER_IMPL_SOURCES",
        "        AND NOT (CONFLUX_HEADER_USE_IMPORT_STD",
        "            OR CONFLUX_HEADER_USE_IMPORT_STD_COMPAT",
        "            OR CONFLUX_HEADER_USE_MODULE_IMPORTS))",
        "    set_source_files_properties(${CONFLUX_BRIDGE_HEADER_IMPL_SOURCES}",
        "        PROPERTIES CXX_SCAN_FOR_MODULES OFF)",
        "endif()",
        "",
        "function(conflux_bridge_resolve_unit out unit mode)",
        "    string(REPLACE \".\" \"/\" _stem \"${unit}\")",
        "    string(REPLACE \":\" \"/\" _stem \"${_stem}\")",
        "    if(mode STREQUAL \"HEADER\")",
        "        set(${out} \"${CONFLUX_GENERATED_INCLUDE_DIR}/${_stem}.hxx\" PARENT_SCOPE)",
        "    else()",
        "        message(FATAL_ERROR \"unknown conflux bridge mode: ${mode}\")",
        "    endif()",
        "endfunction()",
        "",
        "function(conflux_bridge_add_header_interface target)",
        "    add_library(${target} INTERFACE)",
        "    target_include_directories(${target} INTERFACE \"${CONFLUX_GENERATED_INCLUDE_DIR}\" \"${CONFLUX_SRC_ROOT}\")",
        "    target_compile_definitions(${target} INTERFACE",
        "        CONFLUX_HEADER_USE_IMPORT_STD=$<BOOL:${CONFLUX_HEADER_USE_IMPORT_STD}>",
        "        CONFLUX_HEADER_USE_IMPORT_STD_COMPAT=$<BOOL:${CONFLUX_HEADER_USE_IMPORT_STD_COMPAT}>",
        "        CONFLUX_HEADER_USE_MODULE_IMPORTS=$<BOOL:${CONFLUX_HEADER_USE_MODULE_IMPORTS}>)",
        "    if(CMAKE_CXX_STANDARD GREATER_EQUAL 26)",
        "        target_compile_features(${target} INTERFACE cxx_std_26)",
        "    else()",
        "        target_compile_features(${target} INTERFACE cxx_std_23)",
        "    endif()",
        "    if(CONFLUX_HEADER_INTERFACE_WITH_SOURCES AND DEFINED CONFLUX_BRIDGE_HEADER_IMPL_SOURCES)",
        "        set(_conflux_header_impl_target ${target}_impl)",
        "        add_library(${_conflux_header_impl_target} STATIC ${CONFLUX_BRIDGE_HEADER_IMPL_SOURCES})",
        "        target_include_directories(${_conflux_header_impl_target} PRIVATE \"${CONFLUX_GENERATED_INCLUDE_DIR}\" \"${CONFLUX_SRC_ROOT}\")",
        "        target_compile_definitions(${_conflux_header_impl_target} PRIVATE",
        "            CONFLUX_HEADER_USE_IMPORT_STD=$<BOOL:${CONFLUX_HEADER_USE_IMPORT_STD}>",
        "            CONFLUX_HEADER_USE_IMPORT_STD_COMPAT=$<BOOL:${CONFLUX_HEADER_USE_IMPORT_STD_COMPAT}>",
        "            CONFLUX_HEADER_USE_MODULE_IMPORTS=$<BOOL:${CONFLUX_HEADER_USE_MODULE_IMPORTS}>)",
        "        if(CMAKE_CXX_STANDARD GREATER_EQUAL 26)",
        "            target_compile_features(${_conflux_header_impl_target} PUBLIC cxx_std_26)",
        "        else()",
        "            target_compile_features(${_conflux_header_impl_target} PUBLIC cxx_std_23)",
        "        endif()",
        "        target_link_libraries(${target} INTERFACE ${_conflux_header_impl_target})",
        "    endif()",
        "endfunction()",
        "",
        "function(conflux_bridge_add_module_definitions target)",
        "    target_compile_definitions(${target} PUBLIC",
        "        CONFLUX_MODULE_USE_IMPORT_STD=0",
        "        CONFLUX_MODULE_USE_IMPORT_STD_COMPAT=0",
        "        CONFLUX_MODULE_USE_IMPORTS=0",
        "        CONFLUX_MODULE_REEXPORT_IMPORTS=0",
        "        CONFLUX_HEADER_USE_IMPORT_STD=$<BOOL:${CONFLUX_HEADER_USE_IMPORT_STD}>",
        "        CONFLUX_HEADER_USE_IMPORT_STD_COMPAT=$<BOOL:${CONFLUX_HEADER_USE_IMPORT_STD_COMPAT}>",
        "        CONFLUX_HEADER_USE_MODULE_IMPORTS=$<BOOL:${CONFLUX_HEADER_USE_MODULE_IMPORTS}>)",
        "endfunction()",
        "",
    ])
    return "\n".join(lines)


def collect_units(src_root: Path) -> list[ModuleUnit]:
    units: list[ModuleUnit] = []
    for path in sorted([*src_root.rglob("*.cxx"), *src_root.rglob("*.cppm")]):
        unit = discover_module_unit(path, src_root)
        if unit is not None:
            units.append(unit)
    return units


def unit_has_public_body(unit: ModuleUnit) -> bool:
    for line in unit.lines[unit.declaration_index + 1 :]:
        stripped = line.strip()
        if not stripped or stripped.startswith("//") or stripped.startswith("#"):
            continue
        if IMPORT_RE.match(line) is not None:
            continue
        return True
    return False


def public_header_source_unit(unit: ModuleUnit, units_by_name: dict[str, ModuleUnit]) -> ModuleUnit:
    return unit


def manifest_option_value(value: object) -> object:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return str(value)


def manifest_options(args: argparse.Namespace) -> dict[str, object]:
    return {
        key: manifest_option_value(value)
        for key, value in sorted(vars(args).items())
        if key != "bridge_argv"
    }


def generate(args: argparse.Namespace) -> int:
    src_root = args.src.resolve()
    include_out = args.include_out.resolve()
    module_out = args.module_out.resolve() if args.module_out else None
    units = collect_units(src_root)
    units_by_name = {u.module_name: u for u in units}
    exported_units = [u for u in units if u.is_interface]
    interface_units = [u for u in exported_units if not u.is_partition]
    manifest: dict[str, object] = {
        "source_root": str(src_root),
        "include_out": str(include_out),
        "module_out": str(module_out) if module_out else None,
        "write": args.write,
        "interfaces": [],
        "skipped": [],
        "private_includes": [],
        "private_partitions": [],
        "config_header": str(include_out / CONFIG_HEADER_RELPATH),
        "features_header": str(include_out / FEATURES_HEADER_RELPATH),
        "source_overlay": None,
        "consumer_overlays": {},
        "bridge": {
            "script": str(Path(__file__).resolve()),
            "python_executable": sys.executable,
            "python_version": sys.version,
            "argv": list(getattr(args, "bridge_argv", [])),
            "options": manifest_options(args),
            "stdlib_only": True,
        },
    }

    changed = 0
    config_content = render_config_header(collect_config_macros(src_root))
    if write_if_changed(include_out / CONFIG_HEADER_RELPATH, config_content, args.write):
        changed += 1
    if write_if_changed(include_out / FEATURES_HEADER_RELPATH, render_features_header(), args.write):
        changed += 1
    consumer_private_roots = [
        root.resolve()
        for root in (args.examples_src, args.tests_src, args.benchmarks_src)
        if root is not None
    ]
    private_changed, private_includes = emit_private_include_headers(
        src_root,
        include_out,
        exported_units,
        args.write,
        consumer_private_roots)
    changed += private_changed
    manifest["private_includes"] = private_includes

    for unit in interface_units:
        header_relpath = module_to_header_relpath(unit.module_name)
        header_path = include_out / header_relpath
        header_source_unit = public_header_source_unit(unit, units_by_name)
        header_content, header_warnings = transform_to_header(header_source_unit)
        if write_if_changed(header_path, header_content, args.write):
            changed += 1

        module_path = None
        wrapper_warnings: list[str] = []
        if module_out is not None:
            module_path = module_out / unit.relpath
            wrapper_content, wrapper_warnings = transform_to_module_wrapper(unit, header_relpath)
            if write_if_changed(module_path, wrapper_content, args.write):
                changed += 1

        cast_interfaces = manifest["interfaces"]
        assert isinstance(cast_interfaces, list)
        cast_interfaces.append({
            "module": unit.module_name,
            "unit": module_unit_stem(unit.module_name),
            "source": str(unit.relpath),
            "header_source": str(header_source_unit.relpath),
            "header": str(header_path),
            "header_relpath": header_relpath.as_posix(),
            "header_stem": header_relpath.with_suffix("").as_posix(),
            "module_wrapper": str(module_path) if module_path else None,
            "module_source_stem": unit.relpath.with_suffix("").as_posix(),
            "feature_macros": source_line_feature_macros(unit.lines),
            "imports": list(unit.imports),
            "export_imports": list(unit.export_imports),
            "warnings": header_warnings + wrapper_warnings,
        })

    private_partitions = manifest["private_partitions"]
    assert isinstance(private_partitions, list)
    for unit in (u for u in units if u.is_partition):
        header_relpath = module_to_header_relpath(unit.module_name)
        header_path = include_out / header_relpath
        header_content, header_warnings = transform_to_header(unit)
        if write_if_changed(header_path, header_content, args.write):
            changed += 1
        private_partitions.append({
            "module": unit.module_name,
            "unit": module_unit_stem(unit.module_name),
            "source": str(unit.relpath),
            "header": str(header_path),
            "header_relpath": header_relpath.as_posix(),
            "warnings": header_warnings,
        })

    skipped = manifest["skipped"]
    assert isinstance(skipped, list)
    for unit in units:
        if unit in interface_units:
            continue
        reason = "partition" if unit.is_partition else "implementation unit"
        skipped.append({"module": unit.module_name, "source": str(unit.relpath), "reason": reason})

    if args.source_out is not None:
        overlay_changed, overlay_files = emit_source_overlay(src_root, args.source_out.resolve(), units, args.source_mode, args.write)
        changed += overlay_changed
        manifest["source_overlay"] = {
            "root": str(args.source_out.resolve()),
            "mode": args.source_mode,
            "files": overlay_files,
        }

    consumer_overlays = manifest["consumer_overlays"]
    assert isinstance(consumer_overlays, dict)
    for label, source_arg, out_arg in (
        ("examples", args.examples_src, args.examples_out),
        ("tests", args.tests_src, args.tests_out),
        ("benchmarks", args.benchmarks_src, args.benchmarks_out),
    ):
        if source_arg is None or out_arg is None:
            continue
        consumer_changed, consumer_files = emit_consumer_overlay(
            source_arg.resolve(),
            out_arg.resolve(),
            include_out,
            args.write,
            args.consumer_mode)
        changed += consumer_changed
        consumer_overlays[label] = {
            "root": str(out_arg.resolve()),
            "files": consumer_files,
        }

    if args.cmake_fragment_out:
        cmake_path = args.cmake_fragment_out.resolve()
        if write_if_changed(cmake_path, render_cmake_fragment(manifest), args.write):
            changed += 1

    if args.manifest_out:
        manifest_path = args.manifest_out.resolve()
        manifest_content = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
        if write_if_changed(manifest_path, manifest_content, args.write):
            changed += 1

    action = "updated" if args.write else "would update"
    print(f"{action} {changed} files from {len(interface_units)} module interfaces")
    warn_count = sum(len(item.get("warnings", [])) for item in manifest["interfaces"] if isinstance(item, dict))
    if warn_count:
        print(f"warnings: {warn_count}; inspect manifest before wiring generated files into CMake", file=sys.stderr)
        if args.warnings_as_errors:
            return 2
    if not args.write:
        print("dry-run only; pass --write to emit files")
    return 0


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate public headers and module wrappers from conflux module interface units.",
    )
    parser.add_argument("--src", type=Path, default=Path("src"), help="source tree containing .cxx module units")
    parser.add_argument("--include-out", type=Path, default=Path("include"), help="output root for generated headers")
    parser.add_argument("--module-out", type=Path, default=None, help="optional output root for generated module wrappers")
    parser.add_argument("--manifest-out", type=Path, default=Path("build/module_header_bridge_manifest.json"), help="JSON manifest path")
    parser.add_argument("--source-out", type=Path, default=None, help="optional output root for a transformed source overlay")
    parser.add_argument("--source-mode", choices=("module-std-headers", "header"), default="module-std-headers", help="mode for --source-out")
    parser.add_argument("--consumer-mode", choices=("module-std-headers", "header"), default="header", help="mode for example/test/benchmark overlays")
    parser.add_argument("--examples-src", type=Path, default=None, help="optional examples tree to transform for header consumers")
    parser.add_argument("--examples-out", type=Path, default=None, help="optional output root for transformed header-mode examples")
    parser.add_argument("--tests-src", type=Path, default=None, help="optional tests tree to transform for header consumers")
    parser.add_argument("--tests-out", type=Path, default=None, help="optional output root for transformed header-mode tests")
    parser.add_argument("--benchmarks-src", type=Path, default=None, help="optional benchmarks tree to transform for header consumers")
    parser.add_argument("--benchmarks-out", type=Path, default=None, help="optional output root for transformed header-mode benchmarks")
    parser.add_argument("--cmake-fragment-out", type=Path, default=None, help="optional generated CMake helper fragment path")
    parser.add_argument("--warnings-as-errors", action="store_true", help="return non-zero when manifest warnings are produced")
    parser.add_argument("--write", action="store_true", help="write generated files; default is dry-run")
    args = parser.parse_args(argv)
    args.bridge_argv = list(argv)
    return args


def main(argv: list[str] | None = None) -> int:
    return generate(parse_args(sys.argv[1:] if argv is None else argv))


if __name__ == "__main__":
    raise SystemExit(main())
