# cmake/ConfluxPresets.cmake
# Feature preset resolver — CONFLUX_FEATURE_SET selects BUILD_*/WITH_* defaults.
# Explicit user overrides (ON/OFF) are never overwritten; AUTO resolves to preset default.

set(CONFLUX_FEATURE_SET "core" CACHE STRING
    "Feature bundle: core;work;json;http-minimal;http-api;http-api-full;web-server;http-server-complete;complete;dev-core;dev-json;dev-http;dev-all;dev-exp-all;release-core;release-json;release-http-api;release-web-server;release-full")
set_property(CACHE CONFLUX_FEATURE_SET PROPERTY STRINGS
    core work json http-minimal http-api http-api-full web-server http-server-complete complete
    dev-core dev-json dev-http dev-all dev-exp-all release-core release-json release-http-api release-web-server release-full)

# ---------------------------------------------------------------------------
# Tri-state resolver
# ---------------------------------------------------------------------------

function(conflux_resolve out flag_name preset_default)
    set(v "${${flag_name}}")
    if(v STREQUAL "AUTO")
        set(${out} "${preset_default}" CACHE INTERNAL "Resolved conflux component flag" FORCE)
        set(${out} "${preset_default}" PARENT_SCOPE)
    elseif(v STREQUAL "ON")
        set(${out} TRUE CACHE INTERNAL "Resolved conflux component flag" FORCE)
        set(${out} TRUE PARENT_SCOPE)
    elseif(v STREQUAL "OFF")
        set(${out} FALSE CACHE INTERNAL "Resolved conflux component flag" FORCE)
        set(${out} FALSE PARENT_SCOPE)
    else()
        message(FATAL_ERROR "${flag_name}: expected AUTO|ON|OFF, got '${v}'")
    endif()
endfunction()

function(conflux_resolve_provider out flag_name preset_default)
    string(TOUPPER "${${flag_name}}" _provider_value)
    if(_provider_value STREQUAL "AUTO")
        set(_provider_value "${preset_default}")
    endif()
    set(${out} "${_provider_value}" CACHE INTERNAL "Resolved conflux provider flag" FORCE)
    set(${out} "${_provider_value}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------------------
# Component flags — all default to AUTO (resolved by preset)
# ---------------------------------------------------------------------------

set(CONFLUX_BUILD_CORE          "ON"   CACHE STRING "Build core types/utils (always ON)")
set(CONFLUX_BUILD_RUNTIME       "AUTO" CACHE STRING "Build work scheduler + io_uring wrappers")
set(CONFLUX_BUILD_FILE_IO_SYNC  "AUTO" CACHE STRING "Build POSIX file I/O helpers (no liburing)")
set(CONFLUX_BUILD_FILE_MAP      "AUTO" CACHE STRING "Build mmap lease helpers (no liburing)")
set(CONFLUX_BUILD_FILE_IO       "AUTO" CACHE STRING "Build async file I/O (requires liburing)")
set(CONFLUX_BUILD_FILE_WATCH    "AUTO" CACHE STRING "Build inotify/io_uring file watch")
set(CONFLUX_BUILD_SOCKET_IO     "AUTO" CACHE STRING "Build socket I/O + coro")
set(CONFLUX_BUILD_DNS           "AUTO" CACHE STRING "Build async DNS resolution")
set(CONFLUX_BUILD_PROCESS       "AUTO" CACHE STRING "Build child process management")
set(CONFLUX_BUILD_CRYPTO        "AUTO" CACHE STRING "Build AES/hashing/base64")

set(CONFLUX_BUILD_JSON          "AUTO" CACHE STRING "Build JSON parser/DOM/SAX/NDJSON")
set(CONFLUX_BUILD_JSON_FILE     "OFF"  CACHE STRING "Build sync JSON file convenience helpers")

set(CONFLUX_BUILD_TEMPLATES     "AUTO" CACHE STRING "Build template engine")
set(CONFLUX_BUILD_TEMPLATES_WATCH "AUTO" CACHE STRING "Build template hot-reload")

set(CONFLUX_BUILD_HTTP_CORE     "AUTO" CACHE STRING "Build HTTP types/request/response/parser")
set(CONFLUX_BUILD_HTTP_ROUTER   "AUTO" CACHE STRING "Build route matching + middleware chain")
set(CONFLUX_BUILD_HTTP_SERVER   "AUTO" CACHE STRING "Build HTTP server loop")
set(CONFLUX_BUILD_HTTP_CLIENT   "AUTO" CACHE STRING "Build HTTP client")
set(CONFLUX_BUILD_HTTP_JSON     "AUTO" CACHE STRING "Build HTTP JSON helpers")
set(CONFLUX_BUILD_HTTP_STATIC   "AUTO" CACHE STRING "Build static file serving")
set(CONFLUX_BUILD_HTTP_REALTIME "AUTO" CACHE STRING "Build SSE + WebSocket")
set(CONFLUX_BUILD_HTTP_POLICY   "AUTO" CACHE STRING "Build CORS/forwarded/IP filter/rate limit/security")
set(CONFLUX_BUILD_HTTP_AUTH     "AUTO" CACHE STRING "Build auth/cookie signing/CSRF/JWT")
set(CONFLUX_BUILD_HTTP_COMPRESSION "AUTO" CACHE STRING "Build gzip/brotli/zstd compression")
set(CONFLUX_BUILD_HTTP_OBSERVABILITY "AUTO" CACHE STRING "Build metrics/structured_log/tracing/request_id")
set(CONFLUX_BUILD_HTTP_OPENAPI  "AUTO" CACHE STRING "Build OpenAPI generation")
set(CONFLUX_BUILD_HTTP_PROXY    "AUTO" CACHE STRING "Build reverse proxy")
set(CONFLUX_BUILD_HTTP_VHOST    "AUTO" CACHE STRING "Build virtual host dispatch")

set(CONFLUX_BUILD_DB_POSTGRES   "AUTO" CACHE STRING "Build PostgreSQL client")
set(CONFLUX_BUILD_SMTP          "AUTO" CACHE STRING "Build SMTP client")

# ---------------------------------------------------------------------------
# Preset → default resolution
# ---------------------------------------------------------------------------

# Helper: resolve all build flags from preset defaults.
# Each preset calls conflux_resolve for every flag with its intended default.

macro(conflux_apply_preset)
    set(_requested_p "${CONFLUX_FEATURE_SET}")
    set(_p "${CONFLUX_FEATURE_SET}")
    if(_p STREQUAL "dev-core")
        set(_p "core")
    elseif(_p STREQUAL "dev-json")
        set(_p "json")
    elseif(_p STREQUAL "dev-http")
        set(_p "http-api")
    elseif(_p STREQUAL "dev-all")
        set(_p "complete")
    elseif(_p STREQUAL "dev-exp-all")
        set(_p "complete")
        set(CONFLUX_ENABLE_EXPERIMENTAL ON CACHE BOOL
            "Enable experimental runtime features and their tests/benchmarks" FORCE)
    elseif(_p STREQUAL "release-core")
        set(_p "core")
    elseif(_p STREQUAL "release-json")
        set(_p "json")
    elseif(_p STREQUAL "release-http-api")
        set(_p "http-api")
    elseif(_p STREQUAL "release-web-server")
        set(_p "web-server")
    elseif(_p STREQUAL "release-full")
        set(_p "complete")
    endif()

    # ── base defaults: everything OFF ──
    set(_d_RUNTIME       FALSE)
    set(_d_FILE_IO_SYNC  FALSE)
    set(_d_FILE_MAP      FALSE)
    set(_d_FILE_IO       FALSE)
    set(_d_FILE_WATCH    FALSE)
    set(_d_SOCKET_IO     FALSE)
    set(_d_DNS           FALSE)
    set(_d_PROCESS       FALSE)
    set(_d_CRYPTO        FALSE)
    set(_d_JSON          FALSE)
    set(_d_JSON_FILE     FALSE)
    set(_d_TEMPLATES     FALSE)
    set(_d_TEMPLATES_WATCH FALSE)
    set(_d_HTTP_CORE     FALSE)
    set(_d_HTTP_ROUTER   FALSE)
    set(_d_HTTP_SERVER   FALSE)
    set(_d_HTTP_CLIENT   FALSE)
    set(_d_HTTP_JSON     FALSE)
    set(_d_HTTP_STATIC   FALSE)
    set(_d_HTTP_REALTIME FALSE)
    set(_d_HTTP_POLICY   FALSE)
    set(_d_HTTP_AUTH     FALSE)
    set(_d_HTTP_COMPRESSION FALSE)
    set(_d_HTTP_OBSERVABILITY FALSE)
    set(_d_HTTP_OPENAPI  FALSE)
    set(_d_HTTP_PROXY    FALSE)
    set(_d_HTTP_VHOST    FALSE)
    set(_d_DB_POSTGRES   FALSE)
    set(_d_SMTP          FALSE)

    # ── preset overlays (additive) ──

    if(_p STREQUAL "core")
        # Types, utils, generated features. No liburing, no HTTP, no JSON.
    elseif(_p STREQUAL "work")
        set(_d_RUNTIME TRUE)
        set(_d_SOCKET_IO TRUE)
    elseif(_p STREQUAL "json")
        set(_d_JSON TRUE)
    elseif(_p STREQUAL "http-minimal")
        set(_d_RUNTIME TRUE)
        set(_d_FILE_IO_SYNC TRUE)
        set(_d_FILE_MAP TRUE)
        set(_d_FILE_IO TRUE)
        set(_d_SOCKET_IO TRUE)
        set(_d_DNS TRUE)
        set(_d_HTTP_CORE TRUE)
        set(_d_HTTP_ROUTER TRUE)
        set(_d_HTTP_SERVER TRUE)
        set(_d_CRYPTO TRUE)
        set(_d_JSON TRUE)
        set(_d_HTTP_JSON TRUE)
    elseif(_p STREQUAL "http-api")
        set(_d_RUNTIME TRUE)
        set(_d_FILE_IO_SYNC TRUE)
        set(_d_FILE_MAP TRUE)
        set(_d_FILE_IO TRUE)
        set(_d_SOCKET_IO TRUE)
        set(_d_DNS TRUE)
        set(_d_HTTP_CORE TRUE)
        set(_d_HTTP_ROUTER TRUE)
        set(_d_HTTP_SERVER TRUE)
        set(_d_CRYPTO TRUE)
        set(_d_JSON TRUE)
        set(_d_HTTP_JSON TRUE)
        set(_d_HTTP_POLICY TRUE)
        set(_d_HTTP_AUTH TRUE)
    elseif(_p STREQUAL "http-api-full")
        set(_d_RUNTIME TRUE)
        set(_d_FILE_IO_SYNC TRUE)
        set(_d_FILE_MAP TRUE)
        set(_d_FILE_IO TRUE)
        set(_d_SOCKET_IO TRUE)
        set(_d_DNS TRUE)
        set(_d_HTTP_CORE TRUE)
        set(_d_HTTP_ROUTER TRUE)
        set(_d_HTTP_SERVER TRUE)
        set(_d_CRYPTO TRUE)
        set(_d_JSON TRUE)
        set(_d_HTTP_JSON TRUE)
        set(_d_HTTP_POLICY TRUE)
        set(_d_HTTP_AUTH TRUE)
        set(_d_HTTP_OBSERVABILITY TRUE)
        set(_d_HTTP_OPENAPI TRUE)
    elseif(_p STREQUAL "web-server")
        set(_d_RUNTIME TRUE)
        set(_d_FILE_IO_SYNC TRUE)
        set(_d_FILE_MAP TRUE)
        set(_d_FILE_IO TRUE)
        set(_d_SOCKET_IO TRUE)
        set(_d_DNS TRUE)
        set(_d_CRYPTO TRUE)
        set(_d_JSON TRUE)
        set(_d_HTTP_CORE TRUE)
        set(_d_HTTP_ROUTER TRUE)
        set(_d_HTTP_SERVER TRUE)
        set(_d_HTTP_JSON TRUE)
        set(_d_HTTP_STATIC TRUE)
        set(_d_HTTP_COMPRESSION TRUE)
        set(_d_HTTP_REALTIME TRUE)
        set(_d_TEMPLATES TRUE)
    elseif(_p STREQUAL "http-server-complete")
        set(_d_RUNTIME TRUE)
        set(_d_FILE_IO_SYNC TRUE)
        set(_d_FILE_MAP TRUE)
        set(_d_FILE_IO TRUE)
        set(_d_SOCKET_IO TRUE)
        set(_d_DNS TRUE)
        set(_d_CRYPTO TRUE)
        set(_d_JSON TRUE)
        set(_d_TEMPLATES TRUE)
        set(_d_HTTP_CORE TRUE)
        set(_d_HTTP_ROUTER TRUE)
        set(_d_HTTP_SERVER TRUE)
        set(_d_HTTP_CLIENT TRUE)
        set(_d_HTTP_JSON TRUE)
        set(_d_HTTP_STATIC TRUE)
        set(_d_HTTP_REALTIME TRUE)
        set(_d_HTTP_POLICY TRUE)
        set(_d_HTTP_AUTH TRUE)
        set(_d_HTTP_COMPRESSION TRUE)
        set(_d_HTTP_OBSERVABILITY TRUE)
        set(_d_HTTP_OPENAPI TRUE)
        set(_d_HTTP_PROXY TRUE)
        set(_d_HTTP_VHOST TRUE)
    elseif(_p STREQUAL "complete")
        set(_d_RUNTIME TRUE)
        set(_d_FILE_IO_SYNC TRUE)
        set(_d_FILE_MAP TRUE)
        set(_d_FILE_IO TRUE)
        set(_d_FILE_WATCH TRUE)
        set(_d_SOCKET_IO TRUE)
        set(_d_DNS TRUE)
        set(_d_PROCESS TRUE)
        set(_d_CRYPTO TRUE)
        set(_d_JSON TRUE)
        set(_d_TEMPLATES TRUE)
        set(_d_TEMPLATES_WATCH TRUE)
        set(_d_HTTP_CORE TRUE)
        set(_d_HTTP_ROUTER TRUE)
        set(_d_HTTP_SERVER TRUE)
        set(_d_HTTP_CLIENT TRUE)
        set(_d_HTTP_JSON TRUE)
        set(_d_HTTP_STATIC TRUE)
        set(_d_HTTP_REALTIME TRUE)
        set(_d_HTTP_POLICY TRUE)
        set(_d_HTTP_AUTH TRUE)
        set(_d_HTTP_COMPRESSION TRUE)
        set(_d_HTTP_OBSERVABILITY TRUE)
        set(_d_HTTP_OPENAPI TRUE)
        set(_d_HTTP_PROXY TRUE)
        set(_d_HTTP_VHOST TRUE)
        set(_d_DB_POSTGRES TRUE)
        set(_d_SMTP TRUE)
    else()
        message(FATAL_ERROR "Unknown CONFLUX_FEATURE_SET: '${_p}'")
    endif()

    # ── resolve AUTO flags against preset defaults ──
    conflux_resolve(CONFLUX_WANT_RUNTIME       CONFLUX_BUILD_RUNTIME       ${_d_RUNTIME})
    conflux_resolve(CONFLUX_WANT_FILE_IO_SYNC  CONFLUX_BUILD_FILE_IO_SYNC  ${_d_FILE_IO_SYNC})
    conflux_resolve(CONFLUX_WANT_FILE_MAP      CONFLUX_BUILD_FILE_MAP      ${_d_FILE_MAP})
    conflux_resolve(CONFLUX_WANT_FILE_IO       CONFLUX_BUILD_FILE_IO       ${_d_FILE_IO})
    conflux_resolve(CONFLUX_WANT_FILE_WATCH    CONFLUX_BUILD_FILE_WATCH    ${_d_FILE_WATCH})
    conflux_resolve(CONFLUX_WANT_SOCKET_IO     CONFLUX_BUILD_SOCKET_IO     ${_d_SOCKET_IO})
    conflux_resolve(CONFLUX_WANT_DNS           CONFLUX_BUILD_DNS           ${_d_DNS})
    conflux_resolve(CONFLUX_WANT_PROCESS       CONFLUX_BUILD_PROCESS       ${_d_PROCESS})
    conflux_resolve(CONFLUX_WANT_CRYPTO        CONFLUX_BUILD_CRYPTO        ${_d_CRYPTO})
    conflux_resolve(CONFLUX_WANT_JSON          CONFLUX_BUILD_JSON          ${_d_JSON})
    conflux_resolve(CONFLUX_WANT_JSON_FILE     CONFLUX_BUILD_JSON_FILE     ${_d_JSON_FILE})
    conflux_resolve(CONFLUX_WANT_TEMPLATES     CONFLUX_BUILD_TEMPLATES     ${_d_TEMPLATES})
    conflux_resolve(CONFLUX_WANT_TEMPLATES_WATCH CONFLUX_BUILD_TEMPLATES_WATCH ${_d_TEMPLATES_WATCH})
    conflux_resolve(CONFLUX_WANT_HTTP_CORE     CONFLUX_BUILD_HTTP_CORE     ${_d_HTTP_CORE})
    conflux_resolve(CONFLUX_WANT_HTTP_ROUTER   CONFLUX_BUILD_HTTP_ROUTER   ${_d_HTTP_ROUTER})
    conflux_resolve(CONFLUX_WANT_HTTP_SERVER   CONFLUX_BUILD_HTTP_SERVER   ${_d_HTTP_SERVER})
    conflux_resolve(CONFLUX_WANT_HTTP_CLIENT   CONFLUX_BUILD_HTTP_CLIENT   ${_d_HTTP_CLIENT})
    conflux_resolve(CONFLUX_WANT_HTTP_JSON     CONFLUX_BUILD_HTTP_JSON     ${_d_HTTP_JSON})
    conflux_resolve(CONFLUX_WANT_HTTP_STATIC   CONFLUX_BUILD_HTTP_STATIC   ${_d_HTTP_STATIC})
    conflux_resolve(CONFLUX_WANT_HTTP_REALTIME CONFLUX_BUILD_HTTP_REALTIME ${_d_HTTP_REALTIME})
    conflux_resolve(CONFLUX_WANT_HTTP_POLICY   CONFLUX_BUILD_HTTP_POLICY   ${_d_HTTP_POLICY})
    conflux_resolve(CONFLUX_WANT_HTTP_AUTH     CONFLUX_BUILD_HTTP_AUTH     ${_d_HTTP_AUTH})
    conflux_resolve(CONFLUX_WANT_HTTP_COMPRESSION CONFLUX_BUILD_HTTP_COMPRESSION ${_d_HTTP_COMPRESSION})
    conflux_resolve(CONFLUX_WANT_HTTP_OBSERVABILITY CONFLUX_BUILD_HTTP_OBSERVABILITY ${_d_HTTP_OBSERVABILITY})
    conflux_resolve(CONFLUX_WANT_HTTP_OPENAPI  CONFLUX_BUILD_HTTP_OPENAPI  ${_d_HTTP_OPENAPI})
    conflux_resolve(CONFLUX_WANT_HTTP_PROXY    CONFLUX_BUILD_HTTP_PROXY    ${_d_HTTP_PROXY})
    conflux_resolve(CONFLUX_WANT_HTTP_VHOST    CONFLUX_BUILD_HTTP_VHOST    ${_d_HTTP_VHOST})
    conflux_resolve(CONFLUX_WANT_DB_POSTGRES   CONFLUX_BUILD_DB_POSTGRES   ${_d_DB_POSTGRES})
    conflux_resolve(CONFLUX_WANT_SMTP          CONFLUX_BUILD_SMTP          ${_d_SMTP})

    # ── derived: does this preset need liburing? ──
    if(CONFLUX_WANT_RUNTIME OR CONFLUX_WANT_FILE_IO OR CONFLUX_WANT_SOCKET_IO)
        set(CONFLUX_NEEDS_RUNTIME TRUE)
    else()
        set(CONFLUX_NEEDS_RUNTIME FALSE)
    endif()

    # ── provider defaults for AUTO values ──
    # Explicit provider selections still win. These defaults keep small presets
    # from probing or exporting unrelated package dependencies just because a
    # provider default says AUTO.
    set(_d_PROVIDER_JSON_HASH AUTO)
    set(_d_PROVIDER_GZIP AUTO)
    set(_d_PROVIDER_BROTLI AUTO)
    set(_d_PROVIDER_ZSTD AUTO)
    set(_d_PROVIDER_TLS AUTO)
    set(_d_PROVIDER_HTTP2 AUTO)
    set(_d_PROVIDER_HTTP3 AUTO)
    set(_d_PROVIDER_POSTGRES AUTO)
    set(_d_PROVIDER_ARGON2 AUTO)

    if(NOT CONFLUX_WANT_JSON)
        set(_d_PROVIDER_JSON_HASH INTERNAL)
    endif()
    if(NOT CONFLUX_WANT_HTTP_COMPRESSION)
        set(_d_PROVIDER_GZIP OFF)
        set(_d_PROVIDER_BROTLI OFF)
        set(_d_PROVIDER_ZSTD OFF)
    endif()
    if(NOT CONFLUX_WANT_DB_POSTGRES)
        set(_d_PROVIDER_POSTGRES OFF)
    endif()
    if(NOT CONFLUX_WANT_HTTP_AUTH)
        set(_d_PROVIDER_ARGON2 OFF)
    endif()

    if(_p STREQUAL "core" OR _p STREQUAL "work" OR _p STREQUAL "json" OR _p STREQUAL "http-minimal")
        set(_d_PROVIDER_TLS OFF)
        set(_d_PROVIDER_HTTP2 OFF)
        set(_d_PROVIDER_HTTP3 OFF)
    endif()

    if(_requested_p STREQUAL "release-http-api")
        set(_d_PROVIDER_TLS OFF)
        set(_d_PROVIDER_HTTP2 OFF)
        set(_d_PROVIDER_HTTP3 OFF)
        set(_d_PROVIDER_ARGON2 RUNTIME)
    elseif(_requested_p STREQUAL "release-web-server")
        set(_d_PROVIDER_HTTP3 OFF)
    elseif(_requested_p STREQUAL "release-full")
        set(_d_PROVIDER_HTTP3 OFF)
        set(_d_PROVIDER_ARGON2 RUNTIME)
    elseif(_requested_p MATCHES "^release-")
        set(_d_PROVIDER_HTTP3 OFF)
    endif()

    conflux_resolve_provider(CONFLUX_EFFECTIVE_JSON_HASH_PROVIDER CONFLUX_JSON_HASH_PROVIDER ${_d_PROVIDER_JSON_HASH})
    conflux_resolve_provider(CONFLUX_EFFECTIVE_GZIP_PROVIDER CONFLUX_GZIP_PROVIDER ${_d_PROVIDER_GZIP})
    conflux_resolve_provider(CONFLUX_EFFECTIVE_BROTLI_PROVIDER CONFLUX_BROTLI_PROVIDER ${_d_PROVIDER_BROTLI})
    conflux_resolve_provider(CONFLUX_EFFECTIVE_ZSTD_PROVIDER CONFLUX_ZSTD_PROVIDER ${_d_PROVIDER_ZSTD})
    conflux_resolve_provider(CONFLUX_EFFECTIVE_TLS_PROVIDER CONFLUX_TLS_PROVIDER ${_d_PROVIDER_TLS})
    conflux_resolve_provider(CONFLUX_EFFECTIVE_HTTP2_PROVIDER CONFLUX_HTTP2_PROVIDER ${_d_PROVIDER_HTTP2})
    conflux_resolve_provider(CONFLUX_EFFECTIVE_HTTP3_PROVIDER CONFLUX_HTTP3_PROVIDER ${_d_PROVIDER_HTTP3})
    conflux_resolve_provider(CONFLUX_EFFECTIVE_POSTGRES_PROVIDER CONFLUX_POSTGRES_PROVIDER ${_d_PROVIDER_POSTGRES})
    conflux_resolve_provider(CONFLUX_EFFECTIVE_PASSWORD_HASH_ARGON2_PROVIDER CONFLUX_PASSWORD_HASH_ARGON2_PROVIDER ${_d_PROVIDER_ARGON2})
endmacro()
