# Provider AUTO is preset-owned. Keep cache entries as the user-facing request
# and resolve local values before any dependency discovery happens.
set(CONFLUX_JSON_HASH_PROVIDER "${CONFLUX_EFFECTIVE_JSON_HASH_PROVIDER}")
set(CONFLUX_GZIP_PROVIDER "${CONFLUX_EFFECTIVE_GZIP_PROVIDER}")
set(CONFLUX_BROTLI_PROVIDER "${CONFLUX_EFFECTIVE_BROTLI_PROVIDER}")
set(CONFLUX_ZSTD_PROVIDER "${CONFLUX_EFFECTIVE_ZSTD_PROVIDER}")
set(CONFLUX_TLS_PROVIDER "${CONFLUX_EFFECTIVE_TLS_PROVIDER}")
set(CONFLUX_HTTP2_PROVIDER "${CONFLUX_EFFECTIVE_HTTP2_PROVIDER}")
set(CONFLUX_HTTP3_PROVIDER "${CONFLUX_EFFECTIVE_HTTP3_PROVIDER}")
set(CONFLUX_POSTGRES_PROVIDER "${CONFLUX_EFFECTIVE_POSTGRES_PROVIDER}")
set(CONFLUX_PASSWORD_HASH_ARGON2_PROVIDER "${CONFLUX_EFFECTIVE_PASSWORD_HASH_ARGON2_PROVIDER}")
