# ---------------------------------------------------------------------------
# Optional dependencies
# ---------------------------------------------------------------------------

include_guard(GLOBAL)

string(TOUPPER "${CONFLUX_TLS_PROVIDER}" CONFLUX_TLS_PROVIDER_UPPER)
if((CONFLUX_WANT_HTTP_SERVER OR CONFLUX_WANT_HTTP_CLIENT OR CONFLUX_WANT_HTTP_AUTH)
        AND NOT CONFLUX_TLS_PROVIDER_UPPER STREQUAL "OFF")
    find_package(OpenSSL)
endif()
if(CONFLUX_WANT_HTTP_COMPRESSION)
    find_package(ZLIB)
endif()

# ---- OpenSSL / TLS ---------------------------------------------------------
if(NOT CONFLUX_TLS_PROVIDER_UPPER MATCHES "^(AUTO|OPENSSL|OFF)$")
    message(FATAL_ERROR
        "conflux: CONFLUX_TLS_PROVIDER must be AUTO, OPENSSL, or OFF "
        "(got '${CONFLUX_TLS_PROVIDER}')")
endif()
if((CONFLUX_WANT_HTTP_SERVER OR CONFLUX_WANT_HTTP_CLIENT OR CONFLUX_WANT_HTTP_AUTH)
        AND CONFLUX_TLS_PROVIDER_UPPER STREQUAL "OPENSSL"
        AND NOT OpenSSL_FOUND)
    message(FATAL_ERROR "conflux: CONFLUX_TLS_PROVIDER=OPENSSL requires OpenSSL")
endif()
if(NOT (CONFLUX_WANT_HTTP_SERVER OR CONFLUX_WANT_HTTP_CLIENT OR CONFLUX_WANT_HTTP_AUTH)
        OR CONFLUX_TLS_PROVIDER_UPPER STREQUAL "OFF")
    set(CONFLUX_HAS_TLS "false")
elseif(OpenSSL_FOUND)
    set(CONFLUX_HAS_TLS "true")
    set(CONFLUX_RESOLVED_TLS_PROVIDER "OPENSSL" CACHE STRING "Resolved TLS provider" FORCE)
    message(STATUS "conflux: TLS enabled (OpenSSL ${OPENSSL_VERSION})")
else()
    set(CONFLUX_HAS_TLS "false")
    set(CONFLUX_RESOLVED_TLS_PROVIDER "OFF" CACHE STRING "Resolved TLS provider" FORCE)
    if(NOT OpenSSL_FOUND)
        message(STATUS "conflux: TLS disabled (OpenSSL not found)")
    endif()
endif()
if(NOT (CONFLUX_WANT_HTTP_SERVER OR CONFLUX_WANT_HTTP_CLIENT OR CONFLUX_WANT_HTTP_AUTH)
        OR CONFLUX_TLS_PROVIDER_UPPER STREQUAL "OFF")
    set(CONFLUX_RESOLVED_TLS_PROVIDER "OFF" CACHE STRING "Resolved TLS provider" FORCE)
endif()

# ---- zlib / gzip -----------------------------------------------------------
string(TOUPPER "${CONFLUX_GZIP_PROVIDER}" CONFLUX_GZIP_PROVIDER_UPPER)
if(NOT CONFLUX_GZIP_PROVIDER_UPPER MATCHES "^(AUTO|ALL|LIBDEFLATE|ZLIB_NG|ZLIB|ISAL|OFF)$")
    message(FATAL_ERROR
        "conflux: CONFLUX_GZIP_PROVIDER must be AUTO, ALL, LIBDEFLATE, ZLIB_NG, ZLIB, ISAL, or OFF "
        "(got '${CONFLUX_GZIP_PROVIDER}')")
endif()
set(_conflux_gzip_candidates)
if(CONFLUX_WANT_HTTP_COMPRESSION AND LIBDEFLATE_FOUND)
    list(APPEND _conflux_gzip_candidates LIBDEFLATE)
endif()
if(CONFLUX_WANT_HTTP_COMPRESSION AND ZLIB_NG_FOUND)
    list(APPEND _conflux_gzip_candidates ZLIB_NG)
endif()
if(CONFLUX_WANT_HTTP_COMPRESSION AND ZLIB_FOUND)
    list(APPEND _conflux_gzip_candidates ZLIB)
endif()
if(CONFLUX_WANT_HTTP_COMPRESSION AND LIBISAL_FOUND)
    list(APPEND _conflux_gzip_candidates ISAL)
endif()

set(CONFLUX_ENABLE_GZIP_ZLIB FALSE)
set(CONFLUX_ENABLE_GZIP_LIBDEFLATE FALSE)
set(CONFLUX_ENABLE_GZIP_ZLIB_NG FALSE)
set(CONFLUX_ENABLE_GZIP_ISAL FALSE)
set(_conflux_resolved_gzip_provider "OFF")
if(CONFLUX_WANT_HTTP_COMPRESSION AND NOT CONFLUX_GZIP_PROVIDER_UPPER STREQUAL "OFF")
    if(CONFLUX_GZIP_PROVIDER_UPPER STREQUAL "ALL")
        set(_conflux_selected_gzip_backends ${_conflux_gzip_candidates})
        set(_conflux_resolved_gzip_provider "ALL")
    elseif(CONFLUX_GZIP_PROVIDER_UPPER STREQUAL "AUTO")
        if(LIBDEFLATE_FOUND)
            set(_conflux_selected_gzip_backends LIBDEFLATE)
            set(_conflux_resolved_gzip_provider "LIBDEFLATE")
        elseif(ZLIB_NG_FOUND)
            set(_conflux_selected_gzip_backends ZLIB_NG)
            set(_conflux_resolved_gzip_provider "ZLIB_NG")
        elseif(ZLIB_FOUND)
            set(_conflux_selected_gzip_backends ZLIB)
            set(_conflux_resolved_gzip_provider "ZLIB")
        endif()
    else()
        list(FIND _conflux_gzip_candidates "${CONFLUX_GZIP_PROVIDER_UPPER}" _conflux_required_gzip_index)
        if(_conflux_required_gzip_index LESS 0)
            message(FATAL_ERROR
                "conflux: CONFLUX_GZIP_PROVIDER=${CONFLUX_GZIP_PROVIDER_UPPER} was requested but its provider was not found")
        endif()
        set(_conflux_selected_gzip_backends "${CONFLUX_GZIP_PROVIDER_UPPER}")
        set(_conflux_resolved_gzip_provider "${CONFLUX_GZIP_PROVIDER_UPPER}")
    endif()
endif()
set(CONFLUX_RESOLVED_GZIP_PROVIDER "${_conflux_resolved_gzip_provider}" CACHE STRING
    "Resolved gzip backend for this build" FORCE)
foreach(_backend IN LISTS _conflux_selected_gzip_backends)
    if(_backend STREQUAL "ZLIB")
        set(CONFLUX_ENABLE_GZIP_ZLIB TRUE)
    elseif(_backend STREQUAL "LIBDEFLATE")
        set(CONFLUX_ENABLE_GZIP_LIBDEFLATE TRUE)
    elseif(_backend STREQUAL "ZLIB_NG")
        set(CONFLUX_ENABLE_GZIP_ZLIB_NG TRUE)
    elseif(_backend STREQUAL "ISAL")
        set(CONFLUX_ENABLE_GZIP_ISAL TRUE)
    endif()
endforeach()

set(CONFLUX_GZIP_BACKENDS "")
if(CONFLUX_ENABLE_GZIP_ZLIB)
    set(CONFLUX_HAS_ZLIB "true")
    list(APPEND CONFLUX_GZIP_BACKENDS "zlib")
else()
    set(CONFLUX_HAS_ZLIB "false")
endif()
if(CONFLUX_ENABLE_GZIP_LIBDEFLATE)
    list(APPEND CONFLUX_GZIP_BACKENDS "libdeflate")
endif()
if(CONFLUX_ENABLE_GZIP_ZLIB_NG)
    list(APPEND CONFLUX_GZIP_BACKENDS "zlib-ng")
endif()
if(CONFLUX_ENABLE_GZIP_ISAL)
    list(APPEND CONFLUX_GZIP_BACKENDS "isa-l")
endif()

if(NOT CONFLUX_WANT_HTTP_COMPRESSION)
    set(CONFLUX_HAS_COMPRESS "false")
elseif(CONFLUX_GZIP_BACKENDS)
    set(CONFLUX_HAS_COMPRESS "true")
    list(JOIN CONFLUX_GZIP_BACKENDS ", " CONFLUX_GZIP_BACKENDS_STR)
    message(STATUS "conflux: gzip enabled (${CONFLUX_GZIP_BACKENDS_STR})")
else()
    set(CONFLUX_HAS_COMPRESS "false")
    message(STATUS "conflux: gzip disabled (no gzip backend found)")
endif()

# ---- optional gzip backends ------------------------------------------------
if(NOT CONFLUX_WANT_HTTP_COMPRESSION)
    set(CONFLUX_HAS_LIBDEFLATE "false")
elseif(CONFLUX_ENABLE_GZIP_LIBDEFLATE)
    set(CONFLUX_HAS_LIBDEFLATE "true")
    message(STATUS "conflux: libdeflate enabled")
else()
    set(CONFLUX_HAS_LIBDEFLATE "false")
    if(NOT LIBDEFLATE_FOUND)
        message(STATUS "conflux: libdeflate disabled (libdeflate not found)")
    elseif(CONFLUX_GZIP_PROVIDER_UPPER STREQUAL "AUTO")
        message(STATUS "conflux: libdeflate disabled (gzip AUTO selected ${CONFLUX_RESOLVED_GZIP_PROVIDER})")
    else()
        message(STATUS "conflux: libdeflate disabled (CONFLUX_GZIP_PROVIDER=${CONFLUX_GZIP_PROVIDER_UPPER})")
    endif()
endif()

if(NOT CONFLUX_WANT_HTTP_COMPRESSION)
    set(CONFLUX_HAS_ZLIB_NG "false")
elseif(CONFLUX_ENABLE_GZIP_ZLIB_NG)
    set(CONFLUX_HAS_ZLIB_NG "true")
    message(STATUS "conflux: zlib-ng enabled")
else()
    set(CONFLUX_HAS_ZLIB_NG "false")
    if(NOT ZLIB_NG_FOUND)
        message(STATUS "conflux: zlib-ng disabled (zlib-ng not found)")
    elseif(CONFLUX_GZIP_PROVIDER_UPPER STREQUAL "AUTO")
        message(STATUS "conflux: zlib-ng disabled (gzip AUTO selected ${CONFLUX_RESOLVED_GZIP_PROVIDER})")
    else()
        message(STATUS "conflux: zlib-ng disabled (CONFLUX_GZIP_PROVIDER=${CONFLUX_GZIP_PROVIDER_UPPER})")
    endif()
endif()

if(NOT CONFLUX_WANT_HTTP_COMPRESSION)
    set(CONFLUX_HAS_ISAL "false")
elseif(CONFLUX_ENABLE_GZIP_ISAL)
    set(CONFLUX_HAS_ISAL "true")
    message(STATUS "conflux: isa-l enabled")
else()
    set(CONFLUX_HAS_ISAL "false")
    if(NOT LIBISAL_FOUND)
        message(STATUS "conflux: isa-l disabled (libisal not found)")
    elseif(CONFLUX_GZIP_PROVIDER_UPPER STREQUAL "AUTO")
        message(STATUS "conflux: isa-l disabled (gzip AUTO selected ${CONFLUX_RESOLVED_GZIP_PROVIDER})")
    else()
        message(STATUS "conflux: isa-l disabled (CONFLUX_GZIP_PROVIDER=${CONFLUX_GZIP_PROVIDER_UPPER})")
    endif()
endif()

# ---- brotli ----------------------------------------------------------------
string(TOUPPER "${CONFLUX_BROTLI_PROVIDER}" CONFLUX_BROTLI_PROVIDER_UPPER)
if(NOT CONFLUX_BROTLI_PROVIDER_UPPER MATCHES "^(AUTO|SYSTEM|OFF)$")
    message(FATAL_ERROR
        "conflux: CONFLUX_BROTLI_PROVIDER must be AUTO, SYSTEM, or OFF "
        "(got '${CONFLUX_BROTLI_PROVIDER}')")
endif()
if(CONFLUX_WANT_HTTP_COMPRESSION
        AND CONFLUX_BROTLI_PROVIDER_UPPER STREQUAL "SYSTEM"
        AND NOT BROTLI_FOUND)
    message(FATAL_ERROR "conflux: CONFLUX_BROTLI_PROVIDER=SYSTEM requires Brotli pkg-config packages")
endif()
if(NOT CONFLUX_WANT_HTTP_COMPRESSION OR CONFLUX_BROTLI_PROVIDER_UPPER STREQUAL "OFF")
    set(CONFLUX_HAS_BROTLI "false")
elseif(BROTLI_FOUND)
    set(CONFLUX_HAS_BROTLI "true")
    set(CONFLUX_RESOLVED_BROTLI_PROVIDER "SYSTEM" CACHE STRING "Resolved Brotli provider" FORCE)
    message(STATUS "conflux: brotli enabled")
else()
    set(CONFLUX_HAS_BROTLI "false")
    set(CONFLUX_RESOLVED_BROTLI_PROVIDER "OFF" CACHE STRING "Resolved Brotli provider" FORCE)
    if(NOT BROTLI_FOUND)
        message(STATUS "conflux: brotli disabled (libbrotlienc/libbrotlidec not found)")
    endif()
endif()
if(NOT CONFLUX_WANT_HTTP_COMPRESSION OR CONFLUX_BROTLI_PROVIDER_UPPER STREQUAL "OFF")
    set(CONFLUX_RESOLVED_BROTLI_PROVIDER "OFF" CACHE STRING "Resolved Brotli provider" FORCE)
endif()

# ---- zstd ------------------------------------------------------------------
string(TOUPPER "${CONFLUX_ZSTD_PROVIDER}" CONFLUX_ZSTD_PROVIDER_UPPER)
if(NOT CONFLUX_ZSTD_PROVIDER_UPPER MATCHES "^(AUTO|SYSTEM|OFF)$")
    message(FATAL_ERROR
        "conflux: CONFLUX_ZSTD_PROVIDER must be AUTO, SYSTEM, or OFF "
        "(got '${CONFLUX_ZSTD_PROVIDER}')")
endif()
if(CONFLUX_WANT_HTTP_COMPRESSION
        AND CONFLUX_ZSTD_PROVIDER_UPPER STREQUAL "SYSTEM"
        AND NOT ZSTD_FOUND)
    message(FATAL_ERROR "conflux: CONFLUX_ZSTD_PROVIDER=SYSTEM requires libzstd")
endif()
if(NOT CONFLUX_WANT_HTTP_COMPRESSION OR CONFLUX_ZSTD_PROVIDER_UPPER STREQUAL "OFF")
    set(CONFLUX_HAS_ZSTD "false")
elseif(ZSTD_FOUND)
    set(CONFLUX_HAS_ZSTD "true")
    set(CONFLUX_RESOLVED_ZSTD_PROVIDER "SYSTEM" CACHE STRING "Resolved zstd provider" FORCE)
    message(STATUS "conflux: zstd enabled")
else()
    set(CONFLUX_HAS_ZSTD "false")
    set(CONFLUX_RESOLVED_ZSTD_PROVIDER "OFF" CACHE STRING "Resolved zstd provider" FORCE)
    if(NOT ZSTD_FOUND)
        message(STATUS "conflux: zstd disabled (libzstd not found)")
    endif()
endif()
if(NOT CONFLUX_WANT_HTTP_COMPRESSION OR CONFLUX_ZSTD_PROVIDER_UPPER STREQUAL "OFF")
    set(CONFLUX_RESOLVED_ZSTD_PROVIDER "OFF" CACHE STRING "Resolved zstd provider" FORCE)
endif()

# ---- Prometheus metrics (no external dep) ----------------------------------
if(CONFLUX_ENABLE_METRICS)
    set(CONFLUX_HAS_METRICS "true")
    message(STATUS "conflux: metrics enabled")
else()
    set(CONFLUX_HAS_METRICS "false")
    message(STATUS "conflux: metrics disabled")
endif()

# ---- HTTP/2 (requires nghttp2 + TLS) ---------------------------------------
string(TOUPPER "${CONFLUX_HTTP2_PROVIDER}" CONFLUX_HTTP2_PROVIDER_UPPER)
if(NOT CONFLUX_HTTP2_PROVIDER_UPPER MATCHES "^(AUTO|NGHTTP2|OFF)$")
    message(FATAL_ERROR
        "conflux: CONFLUX_HTTP2_PROVIDER must be AUTO, NGHTTP2, or OFF "
        "(got '${CONFLUX_HTTP2_PROVIDER}')")
endif()
if((CONFLUX_WANT_HTTP_SERVER OR CONFLUX_WANT_HTTP_CLIENT)
        AND CONFLUX_HTTP2_PROVIDER_UPPER STREQUAL "NGHTTP2"
        AND (NOT NGHTTP2_FOUND OR NOT CONFLUX_HAS_TLS STREQUAL "true"))
    message(FATAL_ERROR "conflux: CONFLUX_HTTP2_PROVIDER=NGHTTP2 requires libnghttp2 and TLS")
endif()
if(NOT (CONFLUX_WANT_HTTP_SERVER OR CONFLUX_WANT_HTTP_CLIENT)
        OR CONFLUX_HTTP2_PROVIDER_UPPER STREQUAL "OFF")
    set(CONFLUX_HAS_HTTP2 "false")
elseif(NGHTTP2_FOUND AND CONFLUX_HAS_TLS STREQUAL "true")
    set(CONFLUX_HAS_HTTP2 "true")
    set(CONFLUX_RESOLVED_HTTP2_PROVIDER "NGHTTP2" CACHE STRING "Resolved HTTP/2 provider" FORCE)
    message(STATUS "conflux: HTTP/2 enabled (nghttp2)")
else()
    set(CONFLUX_HAS_HTTP2 "false")
    set(CONFLUX_RESOLVED_HTTP2_PROVIDER "OFF" CACHE STRING "Resolved HTTP/2 provider" FORCE)
    if(NOT NGHTTP2_FOUND)
        message(STATUS "conflux: HTTP/2 disabled (libnghttp2 not found)")
    elseif(NOT CONFLUX_HAS_TLS STREQUAL "true")
        message(STATUS "conflux: HTTP/2 disabled (TLS required)")
    endif()
endif()
if(NOT (CONFLUX_WANT_HTTP_SERVER OR CONFLUX_WANT_HTTP_CLIENT)
        OR CONFLUX_HTTP2_PROVIDER_UPPER STREQUAL "OFF")
    set(CONFLUX_RESOLVED_HTTP2_PROVIDER "OFF" CACHE STRING "Resolved HTTP/2 provider" FORCE)
endif()

# ---- HTTP/3 (requires ngtcp2 + nghttp3 + OpenSSL 3.5+ + TLS) ---------------
string(TOUPPER "${CONFLUX_HTTP3_PROVIDER}" CONFLUX_HTTP3_PROVIDER_UPPER)
if(NOT CONFLUX_HTTP3_PROVIDER_UPPER MATCHES "^(AUTO|NGTCP2_NGHTTP3_OPENSSL|OFF)$")
    message(FATAL_ERROR
        "conflux: CONFLUX_HTTP3_PROVIDER must be AUTO, NGTCP2_NGHTTP3_OPENSSL, or OFF "
        "(got '${CONFLUX_HTTP3_PROVIDER}')")
endif()
if(CONFLUX_WANT_HTTP_SERVER
        AND CONFLUX_HTTP3_PROVIDER_UPPER STREQUAL "NGTCP2_NGHTTP3_OPENSSL"
        AND NOT CONFLUX_ENABLE_EXPERIMENTAL)
    message(FATAL_ERROR
        "conflux: explicit HTTP/3 provider requires CONFLUX_ENABLE_EXPERIMENTAL=ON")
endif()
set(CONFLUX_HAS_HTTP3_OPENSSL "false")
if(OpenSSL_FOUND AND OPENSSL_VERSION VERSION_GREATER_EQUAL "3.5.0")
    set(CONFLUX_HAS_HTTP3_OPENSSL "true")
endif()

if(CONFLUX_WANT_HTTP_SERVER
        AND NOT CONFLUX_HTTP3_PROVIDER_UPPER STREQUAL "OFF"
        AND NOT CONFLUX_ENABLE_EXPERIMENTAL)
    message(STATUS "conflux: HTTP/3 deps may be present; disabled because CONFLUX_ENABLE_EXPERIMENTAL=OFF")
endif()

if(NOT CONFLUX_WANT_HTTP_SERVER OR CONFLUX_HTTP3_PROVIDER_UPPER STREQUAL "OFF")
    set(CONFLUX_HAS_HTTP3 "false")
elseif(NGTCP2_FOUND AND NGTCP2_CRYPTO_OSSL_FOUND AND NGHTTP3_FOUND
        AND CONFLUX_HAS_TLS STREQUAL "true"
        AND CONFLUX_HAS_HTTP3_OPENSSL STREQUAL "true"
        AND CONFLUX_ENABLE_EXPERIMENTAL)
    set(CONFLUX_HAS_HTTP3 "true")
    set(CONFLUX_RESOLVED_HTTP3_PROVIDER "NGTCP2_NGHTTP3_OPENSSL" CACHE STRING "Resolved HTTP/3 provider" FORCE)
    message(STATUS "conflux: HTTP/3 enabled (ngtcp2 ${NGTCP2_VERSION}, nghttp3 ${NGHTTP3_VERSION})")
else()
    set(CONFLUX_HAS_HTTP3 "false")
    set(CONFLUX_RESOLVED_HTTP3_PROVIDER "OFF" CACHE STRING "Resolved HTTP/3 provider" FORCE)
    if(NOT CONFLUX_ENABLE_EXPERIMENTAL)
        message(STATUS "conflux: HTTP/3 disabled (CONFLUX_ENABLE_EXPERIMENTAL=OFF)")
    elseif(NOT NGTCP2_FOUND)
        message(STATUS "conflux: HTTP/3 disabled (libngtcp2 not found)")
    elseif(NOT NGTCP2_CRYPTO_OSSL_FOUND)
        message(STATUS "conflux: HTTP/3 disabled (libngtcp2_crypto_ossl not found)")
    elseif(NOT NGHTTP3_FOUND)
        message(STATUS "conflux: HTTP/3 disabled (libnghttp3 not found)")
    elseif(NOT CONFLUX_HAS_TLS STREQUAL "true")
        message(STATUS "conflux: HTTP/3 disabled (TLS required)")
    elseif(NOT CONFLUX_HAS_HTTP3_OPENSSL STREQUAL "true")
        message(STATUS "conflux: HTTP/3 disabled (OpenSSL ${OPENSSL_VERSION} < 3.5.0)")
    endif()
endif()
if(NOT CONFLUX_WANT_HTTP_SERVER OR CONFLUX_HTTP3_PROVIDER_UPPER STREQUAL "OFF")
    set(CONFLUX_RESOLVED_HTTP3_PROVIDER "OFF" CACHE STRING "Resolved HTTP/3 provider" FORCE)
endif()

# ---- Postgres (libpq) ------------------------------------------------------
string(TOUPPER "${CONFLUX_POSTGRES_PROVIDER}" CONFLUX_POSTGRES_PROVIDER_UPPER)
if(NOT CONFLUX_POSTGRES_PROVIDER_UPPER MATCHES "^(AUTO|LIBPQ|OFF)$")
    message(FATAL_ERROR
        "conflux: CONFLUX_POSTGRES_PROVIDER must be AUTO, LIBPQ, or OFF "
        "(got '${CONFLUX_POSTGRES_PROVIDER}')")
endif()
if(CONFLUX_WANT_DB_POSTGRES
        AND CONFLUX_POSTGRES_PROVIDER_UPPER STREQUAL "LIBPQ"
        AND NOT LIBPQ_FOUND)
    message(FATAL_ERROR "conflux: CONFLUX_POSTGRES_PROVIDER=LIBPQ requires libpq")
endif()
if(NOT CONFLUX_WANT_DB_POSTGRES OR CONFLUX_POSTGRES_PROVIDER_UPPER STREQUAL "OFF")
    set(CONFLUX_HAS_DB "false")
elseif(LIBPQ_FOUND)
    set(CONFLUX_HAS_DB "true")
    set(CONFLUX_RESOLVED_POSTGRES_PROVIDER "LIBPQ" CACHE STRING "Resolved PostgreSQL provider" FORCE)
    message(STATUS "conflux: db enabled (libpq ${LIBPQ_VERSION})")
else()
    set(CONFLUX_HAS_DB "false")
    set(CONFLUX_RESOLVED_POSTGRES_PROVIDER "OFF" CACHE STRING "Resolved PostgreSQL provider" FORCE)
    if(NOT LIBPQ_FOUND)
        message(STATUS "conflux: db disabled (libpq not found)")
    endif()
endif()
if(NOT CONFLUX_WANT_DB_POSTGRES OR CONFLUX_POSTGRES_PROVIDER_UPPER STREQUAL "OFF")
    set(CONFLUX_RESOLVED_POSTGRES_PROVIDER "OFF" CACHE STRING "Resolved PostgreSQL provider" FORCE)
endif()

if(CONFLUX_WANT_FILE_WATCH)
    set(CONFLUX_HAS_FILE_WATCH "true")
else()
    set(CONFLUX_HAS_FILE_WATCH "false")
endif()
if(CONFLUX_WANT_TEMPLATES)
    set(CONFLUX_HAS_TEMPLATES "true")
else()
    set(CONFLUX_HAS_TEMPLATES "false")
endif()
if(CONFLUX_WANT_TEMPLATES_WATCH)
    set(CONFLUX_HAS_TEMPLATES_WATCH "true")
else()
    set(CONFLUX_HAS_TEMPLATES_WATCH "false")
endif()
if(CONFLUX_WANT_JSON)
    set(CONFLUX_HAS_JSON "true")
else()
    set(CONFLUX_HAS_JSON "false")
endif()
if(CONFLUX_USE_MOCK_LIBURING)
    set(CONFLUX_BUILD_INFO_MOCK_LIBURING "true")
else()
    set(CONFLUX_BUILD_INFO_MOCK_LIBURING "false")
endif()

execute_process(
    COMMAND git rev-parse --short=12 HEAD
    WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
    OUTPUT_VARIABLE CONFLUX_GIT_COMMIT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)
if(NOT CONFLUX_GIT_COMMIT)
    set(CONFLUX_GIT_COMMIT "unknown")
endif()
if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(CONFLUX_STDLIB_NAME "libstdc++")
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    set(CONFLUX_STDLIB_NAME "libc++/libstdc++")
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    set(CONFLUX_STDLIB_NAME "msvc-stl")
else()
    set(CONFLUX_STDLIB_NAME "unknown")
endif()
set(CONFLUX_STDLIB_VERSION "${CMAKE_CXX_COMPILER_VERSION}")

# Generate the conflux.features module from the template.
configure_file(
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/conflux_features.cxx.in"
    "${CMAKE_CURRENT_BINARY_DIR}/src/conflux_features.cxx"
    @ONLY
)
