set(CONFLUX_EXTERNAL_DEPENDENCY_TOKENS
    LIBURING
    XXHASH
    LIBPQ
    OPENSSL
    ZLIB
    LIBDEFLATE
    ZLIB_NG
    LIBISAL
    BROTLI
    ZSTD
    NGHTTP2
    NGTCP2
    NGTCP2_CRYPTO_OSSL
    NGHTTP3
    ARGON2)

set(CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_LIBURING PkgConfig::LIBURING)
set(CONFLUX_EXTERNAL_DEPENDENCY_KIND_LIBURING PKG_CONFIG)
set(CONFLUX_EXTERNAL_DEPENDENCY_PACKAGES_LIBURING liburing)

set(CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_XXHASH PkgConfig::XXHASH)
set(CONFLUX_EXTERNAL_DEPENDENCY_KIND_XXHASH PKG_CONFIG)
set(CONFLUX_EXTERNAL_DEPENDENCY_PACKAGES_XXHASH libxxhash)

set(CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_LIBPQ PkgConfig::LIBPQ)
set(CONFLUX_EXTERNAL_DEPENDENCY_KIND_LIBPQ PKG_CONFIG)
set(CONFLUX_EXTERNAL_DEPENDENCY_PACKAGES_LIBPQ libpq)

set(CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_OPENSSL OpenSSL::SSL OpenSSL::Crypto)
set(CONFLUX_EXTERNAL_DEPENDENCY_KIND_OPENSSL FIND_PACKAGE)
set(CONFLUX_EXTERNAL_DEPENDENCY_PACKAGES_OPENSSL OpenSSL)

set(CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_ZLIB ZLIB::ZLIB)
set(CONFLUX_EXTERNAL_DEPENDENCY_KIND_ZLIB FIND_PACKAGE)
set(CONFLUX_EXTERNAL_DEPENDENCY_PACKAGES_ZLIB ZLIB)

set(CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_LIBDEFLATE PkgConfig::LIBDEFLATE)
set(CONFLUX_EXTERNAL_DEPENDENCY_KIND_LIBDEFLATE PKG_CONFIG)
set(CONFLUX_EXTERNAL_DEPENDENCY_PACKAGES_LIBDEFLATE libdeflate)

set(CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_ZLIB_NG PkgConfig::ZLIB_NG)
set(CONFLUX_EXTERNAL_DEPENDENCY_KIND_ZLIB_NG PKG_CONFIG)
set(CONFLUX_EXTERNAL_DEPENDENCY_PACKAGES_ZLIB_NG zlib-ng)

set(CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_LIBISAL PkgConfig::LIBISAL)
set(CONFLUX_EXTERNAL_DEPENDENCY_KIND_LIBISAL PKG_CONFIG)
set(CONFLUX_EXTERNAL_DEPENDENCY_PACKAGES_LIBISAL libisal)

set(CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_BROTLI PkgConfig::BROTLI)
set(CONFLUX_EXTERNAL_DEPENDENCY_KIND_BROTLI PKG_CONFIG)
set(CONFLUX_EXTERNAL_DEPENDENCY_PACKAGES_BROTLI libbrotlienc libbrotlidec)

set(CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_ZSTD PkgConfig::ZSTD)
set(CONFLUX_EXTERNAL_DEPENDENCY_KIND_ZSTD PKG_CONFIG)
set(CONFLUX_EXTERNAL_DEPENDENCY_PACKAGES_ZSTD libzstd)

set(CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_NGHTTP2 PkgConfig::NGHTTP2)
set(CONFLUX_EXTERNAL_DEPENDENCY_KIND_NGHTTP2 PKG_CONFIG)
set(CONFLUX_EXTERNAL_DEPENDENCY_PACKAGES_NGHTTP2 libnghttp2)

set(CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_NGTCP2 PkgConfig::NGTCP2)
set(CONFLUX_EXTERNAL_DEPENDENCY_KIND_NGTCP2 PKG_CONFIG)
set(CONFLUX_EXTERNAL_DEPENDENCY_PACKAGES_NGTCP2 libngtcp2)

set(CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_NGTCP2_CRYPTO_OSSL PkgConfig::NGTCP2_CRYPTO_OSSL)
set(CONFLUX_EXTERNAL_DEPENDENCY_KIND_NGTCP2_CRYPTO_OSSL PKG_CONFIG)
set(CONFLUX_EXTERNAL_DEPENDENCY_PACKAGES_NGTCP2_CRYPTO_OSSL libngtcp2_crypto_ossl)

set(CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_NGHTTP3 PkgConfig::NGHTTP3)
set(CONFLUX_EXTERNAL_DEPENDENCY_KIND_NGHTTP3 PKG_CONFIG)
set(CONFLUX_EXTERNAL_DEPENDENCY_PACKAGES_NGHTTP3 libnghttp3)

set(CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_ARGON2 PkgConfig::ARGON2)
set(CONFLUX_EXTERNAL_DEPENDENCY_KIND_ARGON2 PKG_CONFIG)
set(CONFLUX_EXTERNAL_DEPENDENCY_PACKAGES_ARGON2 libargon2)

function(conflux_external_dependency_targets out)
    set(_targets)
    foreach(_token IN LISTS ARGN)
        if(NOT _token IN_LIST CONFLUX_EXTERNAL_DEPENDENCY_TOKENS)
            message(FATAL_ERROR "conflux_external_dependency_targets(${_token}): unknown external dependency token")
        endif()
        list(APPEND _targets ${CONFLUX_EXTERNAL_DEPENDENCY_TARGETS_${_token}})
    endforeach()
    set(${out} ${_targets} PARENT_SCOPE)
endfunction()

function(conflux_existing_external_dependency_targets out)
    set(_targets)
    conflux_external_dependency_targets(_candidate_targets ${ARGN})
    foreach(_target IN LISTS _candidate_targets)
        if(TARGET ${_target})
            list(APPEND _targets ${_target})
        endif()
    endforeach()
    set(${out} ${_targets} PARENT_SCOPE)
endfunction()

function(conflux_link_existing_external_dependency_targets target scope)
    if(NOT scope MATCHES "^(PUBLIC|PRIVATE|INTERFACE)$")
        message(FATAL_ERROR "conflux_link_existing_external_dependency_targets(${target}): invalid link scope '${scope}'")
    endif()
    conflux_existing_external_dependency_targets(_targets ${ARGN})
    if(_targets)
        target_link_libraries(${target} ${scope} ${_targets})
    endif()
endfunction()
